README.md, docs/concept/replication_methods.rst, docs/connectors/taps/jira.rst, docs/connectors/taps/mysql.rst, docs/connectors/taps/postgres.rst, docs/connectors/taps/s3_csv.rst, docs/connectors/taps/snowflake.rst, docs/connectors/targets/postgres.rst, docs/installation_guide/creating_pipelines.rst, docs/installation_guide/installation.rst, docs/installation_guide/running_pipelines.rst, docs/user_guide/metadata_columns.rst, docs/user_guide/resync.rst, docs/user_guide/transformations.rst, docs/user_guide/yaml_config.rst
I added couple docker commands to the project's README to help run the tests for those who choose Docker.
Also fixed some typos here and there in the doc pages.
=> updated doc

dev-project/README.md
Hey, I think mentioning test-project doesn't make sense in the dev-project doc.
Please do review it.
=> Update dev project doc

pipelinewise/fastsync/commons/tap_postgres.py, singer-connectors/tap-postgres/requirements.txt
further details and background about this change at https://github.com/transferwise/pipelinewise-tap-postgres/issues/21
=> lowercase replication slot name

README.md, docs/conf.py, setup.py, singer-connectors/target-redshift/requirements.txt
bumpt to fix "escape sequences" and "logging credentials" issues in target redshift and fastsync
=> Bump version

docs/connectors/targets/redshift.rst, pipelinewise/cli/samples/target_redshift.yml.sample, pipelinewise/fastsync/commons/target_redshift.py, singer-connectors/target-redshift/requirements.txt
Addressing https://github.com/transferwise/pipelinewise-target-redshift/issues/8 for fastsync to Redshift. Customising COPY options is now possible in target YAML files.
=> Configurable COPY options for Redshift

pipelinewise/cli/pipelinewise.py
Fixing https://transferwise.atlassian.net/browse/AP-331
=> AP-331: Add new singer tables to fastsync and singer job

pipelinewise/cli/pipelinewise.py, tests/units/cli/test_cli.py
Exit gracefully on CTRL+C (SIGINT) and kill (SIGTERM):
* Rename tap run log file from `.running` status to `.terminated` automatically. Why? Because if log file remains in running status then we receive `Tap is already running` error message at the next start.
Fixes #214
=> Exit gracefully

dev-project/entrypoint.sh, install.sh, setup.py
* bump snowflake-connector-python==2.0.1
* disable oracle client from dev-environment
* make component install more granular
=> bump snowflake-connector-python==2.0.1

README.md
Some discussion here: https://stackoverflow.com/questions/21079820/how-to-find-pg-config-path
=> "pg_config executable not found" while running install.sh

CHANGELOG.md, docs/conf.py
Added initial changelog including every version
=> 0.10.4 changelog

pipelinewise/cli/tap_properties.py, singer-connectors/tap-kafka/requirements.txt
TODO: add new version for tap-kafka.
=> Extra parameter 'encoding' for tap-kafka.

pipelinewise/fastsync/commons/tap_s3_csv.py, pipelinewise/fastsync/s3_csv_to_snowflake.py, setup.py, tests/units/fastsync/test_fastsync_tap_s3_csv.py
* Support date_overrides given in the configuration when doing FastSync.
* refactored type guessing a bit - no change in behavior.
=> Few improvs

setup.py, singer-connectors/target-snowflake/requirements.txt
https://transferwise.atlassian.net/browse/AP-369
=> 0.11.4: update target-snowflake component version to latest 1.1.7

docs/user_guide/transformations.rst, pipelinewise/fastsync/commons/target_snowflake.py
Applied fix of hidden mask transformation issue - mysql
=> Fix for transformation type Hidden - mysql

dev-project/entrypoint.sh, pipelinewise/fastsync/commons/tap_mysql.py, singer-connectors/tap-mysql/requirements.txt, tests/db/tap_mysql_data.sql
Similar change as https://github.com/transferwise/pipelinewise-tap-mysql/pull/10 but for FastSync.
Will update tap-mysql requirements once it's released.
Will also bump the version in a separate PR.
=> Ap 111 fix

CHANGELOG.md, docs/conf.py, setup.py
This PR makes 0.12.0 of PipelineWise. Some PRs are pending, please don't merge until they are not get merged:
* [pipelinewise - PR309](https://github.com/transferwise/pipelinewise/pull/309)
* [pipelinewise - PR310](https://github.com/transferwise/pipelinewise/pull/310)
* [pipelinewise-tap-mysql - PR12](https://github.com/transferwise/pipelinewise-tap-mysql/pull/12)
=> [RELEASE] Bump to 0.12.0 and add changelog

CHANGELOG.md, setup.py
Bumping patch and updating changelog
=> [RELEASE] Bump version

singer-connectors/tap-postgres/requirements.txt
=> Bump tap-postgres to 1.4.1

pipelinewise/cli/config.py
add inheritable_config options
=> add inheritable_config options

pipelinewise/cli/config.py
Conservative performance defaults
=> Conservative performance defaults

CHANGELOG.md, setup.py
=> [RELEASE] Bump to 0.13.1 and update changelog

CHANGELOG.md, setup.py
Bump version and update changelog.
=> Release 2020-03-09

CHANGELOG.md, dev-project/docker-compose.yml, setup.py, singer-connectors/tap-postgres/requirements.txt
Update changelog and bump version.
=> Release 2020-03-10

README.md, docs/index.rst
PipelineWise is a data reproducer
=> PipelineWise is a data reproducer

CHANGELOG.md, setup.py
Bumping the patch and updating the changelog in prep for the release.
=> Release for 2020-03-13

pipelinewise/fastsync/s3_csv_to_snowflake.py, tests/end_to_end/test_e2e.py
Update type mapping in FS to be the same as singer target-snowflake [here](https://github.com/transferwise/pipelinewise-target-snowflake/blob/e20855b906e2ce6a8fa42375bec51b55f283febe/target_snowflake/db_sync.py#L70).
=> [AP-600] Interpret guessed decimal as float in FS

install.sh
We have some dependency conflict but pip isn't able to grab the right version, it's a known [issue](https://github.com/pypa/pip/issues/4827).
I'm making use of a library called `pip-tools` that fixes this to generate a requirement file with all the right versions.
I also added a `pip check` that looks for conflict and if there are, the script exits with code 1.
=> [AP-601] Generate safe requirements with no conflicts

tests/units/cli/test_config.py
Currently we don't test if the content of the generated singer JSON files from the YAML files are correct or not. This PR extends unit tests add test it.
=> [AP-XXXX] Test generated json file contents

singer-connectors/tap-kafka/requirements.txt, singer-connectors/target-snowflake/requirements.txt
Bump `pipelinewise-target-snowflake` to 1.6.2 and `pipelinewise-tap-kafka` to 2.1.1
=> [AP-XXXX] Bump connectors

CHANGELOG.md, setup.py
=> [RELEASE] v0.14.3

singer-connectors/tap-postgres/requirements.txt
=> tap-postgres version bump

singer-connectors/tap-kafka/requirements.txt
=> [AP-630] Bump tap-kafka

docs/connectors/taps/kafka.rst, docs/connectors/targets/snowflake.rst
Update documentation:
* polishing tap-kafka
* add instruction to target-snowflake IAM roles, env vars and session tokens
=> [DOC] Update documentation

singer-connectors/target-snowflake/requirements.txt
Bump target-snowflake to 1.6.3.
=> [AP-617] Bump target-snowflake

singer-connectors/tap-snowflake/requirements.txt
=> [AP-635] Bump tap-snowflake

CHANGELOG.md, pipelinewise/cli/pipelinewise.py, setup.py
=> [RELEASE] v0.15.0

pipelinewise/fastsync/commons/target_snowflake.py, tests/units/fastsync/commons/test_fastsync_tap_postgres.py, tests/units/fastsync/commons/test_fastsync_target_snowflake.py
Add unit tests for FastSync to Snowflake commons
=> [AP-645] Unit tests for fastsync to snowflake

pipelinewise/fastsync/commons/target_redshift.py, pipelinewise/fastsync/mysql_to_redshift.py, pipelinewise/fastsync/postgres_to_redshift.py, pipelinewise/fastsync/s3_csv_to_redshift.py, setup.py, tests/end_to_end/test_target_redshift.py, tests/units/fastsync/test_s3_csv_to_redshift.py
Add Fastsync from `tap_s3_csv` to `target_redshift`
Including all the end to end tests from the existing fastsync `s3_csv_to_snowflake`
End-to-end tests included.
Unit tests included.
=> [AP-XXXX] Add Fastsync s3_csv to redshift

singer-connectors/tap-oracle/requirements.txt
Bump `pipelinewise-tap-oracle` to 1.0.1
=> [AP-XXXX] Bump tap-oracle

CHANGELOG.md, docs/conf.py, setup.py
**Release v0.16.0 and Changelog**
Please merge only when https://github.com/transferwise/pipelinewise/pull/419 and https://github.com/transferwise/pipelinewise/pull/420 got merged to master.
=> [RELEASE] v0.16.0

.circleci/config.yml, dev-project/.env, dev-project/docker-compose.yml, dev-project/entrypoint.sh, dev-project/mongo/init.sh, dev-project/pipelinewise-config/tap_mongodb.yaml, install.sh, pipelinewise/cli/pipelinewise.py, pipelinewise/cli/samples/tap_mongodb.yml.sample, pipelinewise/cli/schemas/tap.json, pipelinewise/cli/tap_properties.py, singer-connectors/tap-mongodb/requirements.txt, tests/db/tap_mongodb.sh, tests/end_to_end/helpers/env.py, tests/end_to_end/test-project/tap_mongodb_to_pg.yml.template, tests/end_to_end/test_target_postgres.py
With this change, PPW will be able to import and sync mongo taps using Singer
=> [AP-639] Support mongo taps

README.md, dev-project/README.md
Update `README.md` how to start dev env and how to configure and run end to end test cases.
=> [DOC] Updated dev env and testing topics in README.md

.circleci/config.yml, singer-connectors/target-postgres/requirements.txt, singer-connectors/target-redshift/requirements.txt, singer-connectors/target-s3-csv/requirements.txt, singer-connectors/target-snowflake/requirements.txt
Dependency conflicts in some connectors.
1. Install all connectors during build&test step so that conflicts are detected during PR build.
2. Fix detected conflicts.
=> Detect and Fix conflicts 

.circleci/config.yml, tests/end_to_end/test-project/tap_mongodb_to_pg.yml.template, tests/end_to_end/test-project/tap_mongodb_to_sf.yml.template, tests/end_to_end/test-project/tap_mysql_to_pg.yml.template, tests/end_to_end/test-project/tap_mysql_to_pg_buffered_stream.yml.template, tests/end_to_end/test-project/tap_mysql_to_rs.yml.template, tests/end_to_end/test-project/tap_mysql_to_rs_buffered_stream.yml.template, tests/end_to_end/test-project/tap_mysql_to_sf.yml.template, tests/end_to_end/test-project/tap_mysql_to_sf_buffered_stream.yml.template, tests/end_to_end/test-project/tap_postgres_to_pg.yml.template, tests/end_to_end/test-project/tap_postgres_to_rs.yml.template, tests/end_to_end/test-project/tap_postgres_to_sf.yml.template, tests/end_to_end/test-project/tap_s3_csv_to_pg.yml.template, tests/end_to_end/test-project/tap_s3_csv_to_rs.yml.template, tests/end_to_end/test-project/tap_s3_csv_to_sf.yml.template, tests/end_to_end/test_target_postgres.py, tests/end_to_end/test_target_redshift.py, tests/end_to_end/test_target_snowflake.py
No end to end test cases when `stream_buffer_size` is not the default 0.
Add end to end test cases when `stream_buffer_size` is greater than 0.
=> [AP-733] Add end to end tests with custom stream buffer sizes

singer-connectors/target-snowflake/requirements.txt
pipelinewise-target-snowflake 1.6.6 including some bugfixes that not linked to the main pipelinewise:
[target-snowflake Changelog](https://github.com/transferwise/pipelinewise-target-snowflake/blob/master/CHANGELOG.md)
Bump target-snowflake to 1.6.6 to include the bugfixes in the main PPW
=> [AP-767] Bump pipelinewise-target-snowflake

CHANGELOG.md, docs/conf.py, setup.py
**Release v0.16.0 and Changelog**
Please merge only when https://github.com/transferwise/pipelinewise/pull/419 and https://github.com/transferwise/pipelinewise/pull/420 got merged to master.
=> [RELEASE] v0.17.0

pipelinewise/cli/pipelinewise.py, tests/end_to_end/helpers/assertions.py, tests/end_to_end/test_target_postgres.py, tests/end_to_end/test_target_redshift.py, tests/end_to_end/test_target_snowflake.py
`sync_tables` command not working and gives `TypeError: _new_() missing 1 required positional argument: 'config'`
To reproduce in PPW docker local dev env:
```
(pipelinewise) root@ad8b8f133070:/opt/pipelinewise# pipelinewise --tap mariadb_to_pg --target postgres_dwh sync_tables
time=2020-07-03 12:12:09 logger_name=pipelinewise.cli.pipelinewise log_level=INFO message=Syncing tables from mariadb_to_pg (tap-mysql) to postgres_dwh (target-postgres)...
Traceback (most recent call last):
File "/opt/pipelinewise/dev-project/.virtualenvs/pipelinewise/bin/pipelinewise", line 33, in <module>
sys.exit(load_entry_point('pipelinewise', 'console_scripts', 'pipelinewise')())
File "/opt/pipelinewise/pipelinewise/cli/__init__.py", line 160, in main
getattr(ppw_instance, args.command)()
File …
```
=> [AP-792] Fix sync_tables command

CHANGELOG.md, docs/conf.py, setup.py
**Release v0.17.1 and Changelog**
=> [RELEASE] v0.17.1

docs/connectors/taps/google_analytics.rst, docs/connectors/taps/jira.rst, docs/connectors/taps/kafka.rst, docs/connectors/taps/mongodb.rst, docs/connectors/taps/mysql.rst, docs/connectors/taps/oracle.rst, docs/connectors/taps/postgres.rst, docs/connectors/taps/s3_csv.rst, docs/connectors/taps/salesforce.rst, docs/connectors/taps/snowflake.rst, docs/connectors/taps/zendesk.rst, docs/connectors/taps/zuora.rst, docs/index.rst, docs/installation_guide/creating_pipelines.rst, docs/user_guide/alerts.rst, docs/user_guide/yaml_config.rst, pipelinewise/cli/samples/tap_google_analytics.yml.sample, pipelinewise/cli/samples/tap_jira.yml.sample, pipelinewise/cli/samples/tap_kafka.yml.sample, pipelinewise/cli/samples/tap_mongodb.yml.sample, pipelinewise/cli/samples/tap_mysql_mariadb.yml.sample, pipelinewise/cli/samples/tap_oracle.yml.sample, pipelinewise/cli/samples/tap_postgres.yml.sample, pipelinewise/cli/samples/tap_s3_csv.yml.sample, pipelinewise/cli/samples/tap_salesforce.yml.sample, pipelinewise/cli/samples/tap_snowflake.yml.sample, pipelinewise/cli/samples/tap_zendesk.yml.sample, pipelinewise/cli/samples/tap_zuora.yml.sample
Alerts and Slack alert handler not documented
Document Alerts and Slack alert handler
=> [DOC] Alerts and slack alert handler

dev-project/pipelinewise-config/config.yml, docs/user_guide/alerts.rst, pipelinewise/cli/alert_handlers/victorops_alert_handler.py, pipelinewise/cli/alert_sender.py, pipelinewise/cli/samples/config.yml, pipelinewise/cli/schemas/config.json, setup.py, tests/units/cli/test_alert_sender.py
PPW cannot send alerts to create incidents on victorops.
Add VictorOps alert handler to PPW.
=> [AP-531] Add VictorOps alert handler

CHANGELOG.md, docs/conf.py, setup.py
**Release v0.18.0 and Changelog**
=> [RELEASE] v0.18.0

CHANGELOG.md, docs/conf.py, setup.py
**Release v0.18.1 and Changelog**
=> [RELEASE] v0.18.1

CHANGELOG.md, docs/conf.py, setup.py
**Release v0.19.0 and Changelog**
=> [RELEASE] v0.19.0

CHANGELOG.md, docs/conf.py, setup.py
**Release v0.20.0 and Changelog**
=> [RELEASE] v0.20.0

CHANGELOG.md, setup.py
**Release v0.20.2 and Changelog**
=> [RELEASE] v0.20.2

docs/connectors/taps/s3_csv.rst, docs/connectors/targets/redshift.rst, docs/connectors/targets/s3_csv.rst, docs/connectors/targets/snowflake.rst, pipelinewise/cli/samples/tap_s3_csv.yml.sample, pipelinewise/cli/samples/target_redshift.yml.sample, pipelinewise/cli/samples/target_s3_csv.yml.sample, pipelinewise/cli/samples/target_snowflake.yml.sample, pipelinewise/fastsync/commons/target_redshift.py, pipelinewise/fastsync/commons/target_snowflake.py, singer-connectors/tap-s3-csv/requirements.txt, singer-connectors/target-redshift/requirements.txt
Fastsync to snowflake is using hard coded `aws_access_key_id` and `aws_secret_access_key` to connect to S3. This is not great because it requires hard coded credentials in tap YAMLs. This PR is the equivalent of https://github.com/transferwise/pipelinewise-target-snowflake/commit/85ebb71809a46b6a804cb64b9d42e09e716c6cce but for Snowflake fastsync and adds **Profile Based and Environment Variable based** authentication methods to S3.
This PR updates lot of **documentation and sample YAML** with examples of using profile based and env var based S3 authentications across every supported s3 based connector: `tap-s3-csv`, `target-snowflake`, `target-s3-csv`, `target-redshift`
1. Implement https://github.com/transferwise/pipelinewise-target-snowflake/commit/85ebb71809a46b6a804cb64b9d42e09e716c6c …
=> [AP-822] Add and doc fastsync S3 profile and env var based auths

CHANGELOG.md, docs/conf.py, setup.py
**Release v0.21.0 and Changelog**
=> [RELEASE] v0.21.0

CHANGELOG.md, setup.py
=> Release 0.21.1

CHANGELOG.md, setup.py
=> Patch: increase resources

CHANGELOG.md, setup.py
**Release v0.21.3 and Changelog**
=> [RELEASE] v0.21.3

CHANGELOG.md, docs/conf.py, setup.py
**Release v0.22.0 and Changelog**
=> [RELEASE] 0.22.0

singer-connectors/tap-mysql/requirements.txt
An info log in tap-mysql creating lots of logs and causing the files to be huge
install tap-mysql 1.3.6
=> [FIX] tap mysql generating lots of logs

singer-connectors/target-s3-csv/requirements.txt
target-s3-csv writes temp files to system `/tmp` instead of PPW specific `~/.pipelinewise/tmp` directory.
This can be a problem if not enough space in `/tmp` to write large temp files.
Bump [pipelinewise-target-s3-csv](https://github.com/transferwise/pipelinewise-target-s3-csv) to v1.4.0 that adds the `temp_dir` option to write temporary files to custom locations. PPW automatically passing the `temp_dir` parameter to every target component so no further changes required to write temp files out of `/tmp`. 
=> [AP-846] Bump target-s3-csv

README.md
=> * Updated README

CHANGELOG.md, docs/conf.py, setup.py
**Release v0.22.1 and Changelog**
=> [RELEASE] v0.22.1

CHANGELOG.md, docs/conf.py, setup.py
**Release v0.24.0 and Changelog**
=> [RELEASE] v0.24.0

CHANGELOG.md, docs/conf.py, setup.py
**Release v0.24.1 and Changelog**
=> [RELEASE] v0.24.1

.github/workflows/codeql-analysis.yml
No code scanning to finding security vulnerabilities and errors in the code base
Enabling automatic code scanning with the help of Github's CodeQL. 
=> [AP-NNN] Enable code analysis

docs/connectors/taps/postgres.rst
Doc missing a query about how to handle future tables created in PG source.
Add a recommend query to run to avoid tables not being visible to ppw user.
=> [Doc] Update PG tap documentation

docs/connectors/taps/slack.rst, pipelinewise/cli/samples/tap_slack.yml.sample, singer-connectors/tap-slack/requirements.txt
`pipelinewise-tap-slack` 1.0.1 currently lacking:
* Incremental bookmarks are not updating correctly
* User emails are not loaded into `user.profiles`
* Message attachments are not loaded into `message.attachments`
Bump `pipelinewise-tap-slack` to 1.1.0 where all the above issues and enhancements are addressed. 
=> [AP-860] bump and document pipelinewise-tap-slack

CHANGELOG.md, setup.py
**Release v0.25.0 and Changelog**
=> [RELEASE] v0.25.0

CHANGELOG.md, docs/conf.py, setup.py
**Release v0.26.0 and Changelog**
=> [RELEASE] v0.26.0

README.md, docs/index.rst, docs/installation_guide/installation.rst, docs/project/licenses.rst
License relationship between pipelinewise and forked taps are not clarified in the documentation.
Add License section to the documention with details of licenses.
=> [DOC] Update license conditions

CHANGELOG.md, setup.py
=> Release 0.27.0

docs/installation_guide/creating_pipelines.rst
Added documentation for code added in #588 .
Updated documentation.
=> Added documentation on how to use envrionment variables in YAML configs.

CHANGELOG.md, setup.py
=> Release 0.28.1

docs/conf.py, docs/connectors/taps.rst
Twilio logo on the main page is not aligned nicely 
Fix alignment
=> [DOC] Fix alignment of twilio logo

CHANGELOG.md, docs/conf.py, setup.py
=> Release 0.30.0

CONTRIBUTING.md, motd, setup.py
Transferwise rebrands to Wise
Update name
=> Change Transferwise to Wise

CHANGELOG.md, docs/conf.py, setup.py
=> Release 0.31.0

singer-connectors/tap-mysql/requirements.txt
Data loss in mysql binlog replication
Details in this PR https://github.com/transferwise/pipelinewise-tap-mysql/pull/57
Use ppw-tap-mysql v1.4.2
=> [AP-958][Bug Fix] Data loss in mysql binlog replication

.circleci/config.yml
No such thing as `upload-build` context
don't use any context
=> [CI] Fix context in deployment step

.circleci/config.yml
Failing to upload docker image due to missing cli option
Set context
=> [CI] Set context in docker upload step 

CHANGELOG.md, docs/conf.py, setup.py
=> Release 0.32.0

docs/connectors/taps/mysql.rst, docs/connectors/taps/postgres.rst, pipelinewise/cli/config.py, pipelinewise/cli/samples/tap_mysql_mariadb.yml.sample, pipelinewise/cli/samples/tap_postgres.yml.sample, pipelinewise/cli/schemas/tap.json, pipelinewise/fastsync/commons/split_gzip.py, pipelinewise/fastsync/commons/tap_mongodb.py, pipelinewise/fastsync/commons/tap_mysql.py, pipelinewise/fastsync/commons/tap_postgres.py, pipelinewise/fastsync/commons/target_snowflake.py, pipelinewise/fastsync/mysql_to_snowflake.py, pipelinewise/fastsync/postgres_to_snowflake.py, tests/end_to_end/test-project/tap_mysql_to_sf_split_large_files.yml.template, tests/end_to_end/test-project/tap_postgres_to_sf_split_large_files.yml.template, tests/end_to_end/test_target_snowflake.py, tests/units/cli/resources/test_yaml_config/tap_test.yml, tests/units/cli/test_config.py, tests/units/fastsync/commons/test_fastsync_tap_mongodb.py, tests/units/fastsync/commons/test_split_gzip.py
FastSync should be able to split large files to multiple pieces to optimise load performance in the supported target databases that can benefit from it like Snowflake and Redshift.
Create `SplitGzipFile` file like object to stream data and write multipart gzip files automatically.
New configurable options in the YAML files from postgres and mysql to snowflake targets:
* `split_large_files`: Split large batch files to smaller pieces. (Default: False)
* `split_file_chunk_size_mb`: File chunk sizes if `split_large_files` enabled. (Default: 1000)
* `split_file_max_chunks`: Max number of chunks if `split_large_files` enabled. (Default: 20)
=> [AP-986] Add SplitGzipFile file type object to write multipart zips

singer-connectors/target-snowflake/requirements.txt
Bump target-snowflake
https://github.com/transferwise/pipelinewise-target-snowflake/blob/master/CHANGELOG.md#1131-2021-07-15
=> target-snowflake 1.13.1

singer-connectors/tap-github/requirements.txt, singer-connectors/tap-s3-csv/requirements.txt
Features and bugixes added to [pipelinewise-tap-github](https://github.com/transferwise/pipelinewise-tap-github]) and [pipelinewise-tap-s3-csv](https://github.com/transferwise/pipelinewise-tap-s3-csv)
Bump connectors to latest.
=> Bump connectors

.circleci/config.yml
We're not building an image tagged with `latest`
Specify additional tag for k8s deployer
=> CI: Build image with tag latest

.circleci/config.yml
We need to build image with tag `latest`, env must be a string, not list
use string, not list
=> CI - Fix: Change additional tags from list to string

docs/connectors/taps/github.rst
Updating documentation with new fields
Public doc changes on General Properties and Github connection details
=> Update documentation with the new github tap functionality

pipelinewise/cli/alert_sender.py, pipelinewise/cli/commands.py, pipelinewise/cli/config.py, pipelinewise/cli/pipelinewise.py, pipelinewise/cli/utils.py, pipelinewise/fastsync/commons/split_gzip.py, pipelinewise/fastsync/commons/target_snowflake.py, pipelinewise/fastsync/commons/transform_utils.py, pipelinewise/fastsync/commons/utils.py, setup.py, tests/end_to_end/helpers/assertions.py, tests/end_to_end/helpers/env.py, tests/end_to_end/test_target_snowflake.py, tests/units/cli/test_alert_sender.py, tests/units/cli/test_cli.py, tests/units/cli/test_cli_utils.py, tests/units/cli/test_cli_utils_tap_github.py, tests/units/cli/test_commands.py, tests/units/cli/test_config.py, tests/units/fastsync/commons/test_fastsync_tap_mysql.py
Pylint is outdated reported by dependabot at https://github.com/transferwise/pipelinewise/pull/782
Bump pylint to latest and fix pylint warnings.
=> Bumpy pylint from 2.8.3 to 2.10.2

docs/project/contribution.rst, pipelinewise/cli/constants.py
https://github.com/transferwise/pipelinewise/issues/800
Add all connectors to Enum
=> [gh-issue-800] Add all connectors to enum

docs/user_guide/transformations.rst, pipelinewise/cli/schemas/tap.json, pipelinewise/fastsync/commons/transform_utils.py, singer-connectors/transform-field/requirements.txt, tests/db/tap_mysql_data.sql, tests/db/tap_postgres_data.sql, tests/end_to_end/test-project/tap_mysql_to_pg.yml.template, tests/end_to_end/test-project/tap_mysql_to_pg_buffered_stream.yml.template, tests/end_to_end/test-project/tap_mysql_to_sf.yml.template, tests/end_to_end/test-project/tap_mysql_to_sf_buffered_stream.yml.template, tests/end_to_end/test-project/tap_postgres_to_pg.yml.template, tests/end_to_end/test-project/tap_postgres_to_sf.yml.template, tests/units/fastsync/commons/test_fastsync_target_postgres.py, tests/units/fastsync/commons/test_fastsync_target_snowflake.py, tests/units/fastsync/commons/test_transform_utils.py
Added a new MASK-STRING-SKIP-ENDS transformation.
If it fixes a bug or resolves a feature request, be sure to link to that issue._
New transformation added. The transformation enables user to mask a string except the start and end n-characters.
=> Feature: Added new MASK-STRING-SKIP-ENDS transformation

singer-connectors/tap-postgres/requirements.txt
ppw-tap-postgres has some patches
Bump patch in tap-postgres 
=> [Fix] Bump pipelinewise-tap-postgres patch

Dockerfile, Makefile
connections build argument was not handling correctly after moving to use the Makefile
Docker file is updated to handle all different cases of build argument
=> [AP-1070] Fixed handling build arguments

CHANGELOG.md, setup.py
=> Release 0.36.0

singer-connectors/target-snowflake/requirements.txt
Missed bumping target- in previous PR
bump version
=> Release PR amended: Bump target SF to 1.14.0

Makefile, dev-project/entrypoint.sh
trying to create local PPW dev-env and docker-compose up --build gives make: *** No rule to make target 'pipelinewise'. Stop.
update docker-compose to have correct paths.
=> [AP-1073] fixed make process in docker-compose file

CHANGELOG.md, setup.py
=> Release 0.37.0

CHANGELOG.md, setup.py
=> Release v0.37.1

singer-connectors/tap-github/requirements.txt
=> bump tap github to v1.0.3

CHANGELOG.md, setup.py
=> release v0.37.2

Dockerfile, Dockerfile.barebone, dev-project/docker-compose.yml, pytest.ini, singer-connectors/target-postgres/requirements.txt
We've been running on 3.7 for years, Python 3.8 is stable.
Upgrade base image to python 3.8
=> AP-1098 Upgrade base image to Python 3.8

CHANGELOG.md, Makefile, setup.py, singer-connectors/tap-s3-csv/requirements.txt
=> release v0.41.0

.github/workflows/linter.yml, .github/workflows/tests.yml, setup.py
- Python 3.6 is end of life.
- Python 3.9 and 3.10 are currently untested.
- Remove Python 3.6 from test matrix
- Add Python 3.9 to test matrix.
- Python 3.10 does not pass so don't add it.
- Set the correct `python_requires` in `setup.py`
_Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. 
If it fixes a bug or resolves a feature request, be sure to link to that issue._
=> Update tested Python versions

.github/workflows/linter.yml, Dockerfile.CI, scripts/check_any_file_changed.py
=> [AP-1123] run linting in docker

tests/end_to_end/helpers/assertions.py
improve assert_all_columns_exist test helper function
=> improve assert_all_columns_exist test helper function

pipelinewise/fastsync/postgres_to_snowflake.py, tests/end_to_end/test-project/tap_postgres_to_sf_split_large_files.yml.template, tests/end_to_end/test_target_snowflake.py
=> [AP-1154] fix E2E pg_to_sf tests

.github/workflows/connectors.yml, singer-connectors/tap-snowflake/requirements.txt
Modify CI to check singer connectors installable for 3.7 3.8 3.9
=> check singer connectors installable for 3.7 3.8 3.9

.github/workflows/e2e_tests.yml, .github/workflows/lint_unit_tests.yml, Dockerfile.CI
=> [AP-1144] run unit tests in docker

singer-connectors/tap-kafka/requirements.txt
There is a new release for tap-kaka
bump tap_kafka to 6.0.0
=> bump tap_kafka to 6.0.0

docs/connectors/taps/adwords.rst, docs/connectors/taps/github.rst, docs/connectors/taps/google_analytics.rst, docs/connectors/taps/jira.rst, docs/connectors/taps/kafka.rst, docs/connectors/taps/mixpanel.rst, docs/connectors/taps/mongodb.rst, docs/connectors/taps/mysql.rst, docs/connectors/taps/oracle.rst, docs/connectors/taps/postgres.rst, docs/connectors/taps/s3_csv.rst, docs/connectors/taps/salesforce.rst, docs/connectors/taps/shopify.rst, docs/connectors/taps/slack.rst, docs/connectors/taps/snowflake.rst, docs/connectors/taps/twilio.rst, docs/connectors/taps/zendesk.rst, docs/connectors/taps/zuora.rst, docs/user_guide/alerts.rst
Documentation for setting specific slack channel
Documentation update
=> [AP-1173] Updated documentation for specific slack channel setting

singer-connectors/target-snowflake/requirements.txt
detailed here: https://github.com/transferwise/pipelinewise-target-snowflake/pull/262
patch target https://github.com/transferwise/pipelinewise-target-snowflake/releases/tag/v2.0.1
=> AP-1204 AP-1205: Patch target-snowflake

docs/user_guide/scheduling.rst
Tweaking some PipelineWise documentation
Documentation tweaks
=> Tweak some PipelineWise documentation

pipelinewise/fastsync/commons/tap_postgres.py, pipelinewise/fastsync/partialsync/postgres_to_snowflake.py, pipelinewise/fastsync/partialsync/utils.py, setup.py, tests/units/partialsync/resources/test_partial_sync/target_snowflake/tap_postgres/config.json, tests/units/partialsync/test_partial_sync_utils.py, tests/units/partialsync/test_postgres_to_snowflake.py, tests/units/partialsync/utils.py
merging postgres implementation
=> AP-12-16 added postgres to snowflake module

pipelinewise/cli/__init__.py, pipelinewise/cli/commands.py, pipelinewise/cli/errors.py, pipelinewise/cli/pipelinewise.py, pipelinewise/cli/utils.py, setup.py, tests/units/cli/resources/test_partial_sync/config.json, tests/units/cli/resources/test_partial_sync/target_not_supported/config.json, tests/units/cli/resources/test_partial_sync/target_not_supported/tap_mysql/config.json, tests/units/cli/resources/test_partial_sync/target_snowflake/config.json, tests/units/cli/resources/test_partial_sync/target_snowflake/tap_mysql/config.json, tests/units/cli/resources/test_partial_sync/target_snowflake/tap_mysql/inheritable_config.json, tests/units/cli/resources/test_partial_sync/target_snowflake/tap_mysql/properties.json, tests/units/cli/resources/test_partial_sync/target_snowflake/tap_mysql/state.json, tests/units/cli/resources/test_partial_sync/target_snowflake/tap_mysql/transformation.json, tests/units/cli/resources/test_partial_sync/target_snowflake/tap_mysql_disabled/config.json, tests/units/cli/resources/test_partial_sync/target_snowflake/tap_no_state/config.json, tests/units/cli/resources/test_partial_sync/target_snowflake/tap_no_state/inheritable_config.json, tests/units/cli/resources/test_partial_sync/target_snowflake/tap_no_state/log/target_snowflake-tap_no_state-20220503_151213.partialsync.log.failed, tests/units/cli/resources/test_partial_sync/target_snowflake/tap_no_state/properties.json, tests/units/cli/resources/test_partial_sync/target_snowflake/tap_no_state/transformation.json, tests/units/cli/resources/test_partial_sync/target_snowflake/tap_not_support/config.json, tests/units/cli/test_partial_sync.py
Structure for partial sync CLI
=> [AP-1214] Partial sync cli structure

CHANGELOG.md, setup.py
Releasing 0.46.0
- Prepare CHANGELOG for 0.46.0
- Update PipelineWise to 0.46.0
=> Prepare for release 0.46.0

pipelinewise/fastsync/commons/tap_mysql.py, pipelinewise/fastsync/commons/tap_postgres.py, pipelinewise/fastsync/commons/utils.py, pipelinewise/fastsync/partialsync/mysql_to_snowflake.py, pipelinewise/fastsync/partialsync/postgres_to_snowflake.py, pipelinewise/fastsync/partialsync/utils.py, setup.py, tests/units/partialsync/resources/test_partial_sync/target_snowflake/tap_mysql/config.json, tests/units/partialsync/resources/test_partial_sync/target_snowflake/tap_mysql/properties.json, tests/units/partialsync/resources/test_partial_sync/target_snowflake/tap_mysql/transformation.json, tests/units/partialsync/resources/test_partial_sync/target_snowflake/tap_postgres/config.json, tests/units/partialsync/resources/test_partial_sync/tmp/target_config_tmp.json, tests/units/partialsync/test_mysql_to_snowflake.py, tests/units/partialsync/test_partial_sync_utils.py, tests/units/partialsync/test_postgres_to_snowflake.py, tests/units/partialsync/utils.py
This is another subtest for partial sync and it includes the MySQL and Postgres modules to SF partial sync.
It will be merged into AP-1149 branch and then all subtasks will be merged together into the master
=> [AP-1215] Implementation for MySQL and Postgres to SF partial sync

setup.py
new release of `chardet` (5.0.0) is not compatible with `messytables` (0.15.*)
Adding `chardet` (4.0.0) into the requirements.
=> [AP-1239] Added chardet 4.0.0 in the requirements

pipelinewise/fastsync/commons/tap_mysql.py, pipelinewise/fastsync/commons/tap_postgres.py, pipelinewise/fastsync/partialsync/utils.py, tests/units/partialsync/test_partial_sync_utils.py
Single quotes are missed in where clause and it does not to support all column types
adding single quotes in where clause
=> [AP-1241]Fixed where clause for partial sync

singer-connectors/tap-kafka/requirements.txt
=> update tap-kafka to v7.1.0

pipelinewise/cli/pipelinewise.py, tests/units/cli/test_partial_sync.py
There was not any check for selected table in config 
another check for selection
=> [AP-1249] Fixed check for selected

CHANGELOG.md, setup.py
=> Release 0.48.1

tests/end_to_end/target_snowflake/__init__.py
SF e2e tests are failing if SF environment variables are not set
checking and skipping the test before dropping the schema from SF
=> [AP-1272] Fix for SF e2e tests credential checks

singer-connectors/tap-mysql/requirements.txt
Update to the latest bugfix release that fixes some decoding issues.
mysql-replication library was updated in this release, this fixes a regression in 0.30 related to decoding.
https://github.com/transferwise/pipelinewise-tap-mysql/issues/121
https://github.com/transferwise/pipelinewise-tap-mysql/pull/111
=> Bump pipelinewise-tap-mysql

docs/concept/replication_methods.rst
Update docs : clarify normal INCREMENTAL behavior
Update docs : clarify normal INCREMENTAL behavior
=> Update docs : clarify normal INCREMENTAL behavior

pipelinewise/fastsync/mysql_to_snowflake.py, pipelinewise/fastsync/postgres_to_snowflake.py
Seems glob.glob has some bug!
Added log message to investigate
=> [AP-1333] added log for data loss investigation

CHANGELOG.md, setup.py, singer-connectors/tap-kafka/requirements.txt, singer-connectors/tap-postgres/requirements.txt
=> Release 0.51.0

pipelinewise/cli/pipelinewise.py
takes all tables for fastsync if a table does not exist in state
send the list of selected fastsync tables to the method for running the sync on them
=> [AP-1393] fixed selected fastsync tables

.github/PULL_REQUEST_TEMPLATE.md
To try to reduce the number of future issues, it's better to help both the contributor and the reviewer if there is a high level description of not only the new feature but also the test scenarios that are covered with the new added unit tests.
Change this PR's description to require explicit listing of test scenarios when making changes
=> AP-1404 Changed the description to require a more thorough description

pipelinewise/cli/pipelinewise.py
after sending SIGTERM , it could not kill the child processes.
parantheses were missed!
=> [AP-1394] bug fix for graceful exit

CHANGELOG.md, setup.py
=> Release 0.52.1

CHANGELOG.md, setup.py
=> Release 0.53.0

pipelinewise/cli/pipelinewise.py
stop_tap command does not delete the pid file.
make sure pid file is deleted in stop_tap command
=> [AP-1445] remove pid file if exists in stop_tap command.

.github/workflows/e2e_tests.yml, dev-project/entrypoint.sh, singer-connectors/tap-mysql/requirements.txt
https://github.com/transferwise/pipelinewise-tap-mysql/pull/156
bumping ppw-tap-mysql
Misc: adding timeout to steps that wait for container as there is no need to wait indefinitely. 
=> AP-1477: Bump ppw-tap-mysql

CHANGELOG.md, setup.py
=> Release 0.53.4

CHANGELOG.md, setup.py
=> Release 0.54.0

singer-connectors/tap-mysql/requirements.txt
https://github.com/transferwise/pipelinewise-tap-mysql/pull/163
Bump ppw-tap-mysql to 1.5.5
=> LookupError: unknown encoding: utf8mb3

CHANGELOG.md, setup.py
=> Release 0.55.0

CHANGELOG.md, setup.py, singer-connectors/tap-kafka/requirements.txt
pipelinewise-tap-kafka patch has been release 8.2.1
Bump tap-kafka
=> Release 0.53.3

dev-project/entrypoint.sh, dev-project/mongo/init_rs.sh, singer-connectors/target-postgres/requirements.txt
Local dev not working due to some changes in mongo and postgres on 🍎M CPUs
Minor updates to make local-dev great again
=> Minor updates to make local-dev great again

CHANGELOG.md, setup.py
Jira tap was having some issues, this update is an attempt at fixing them before diving a bit deeper.
There is also an update on some underlying dependencies.
Updated some dependencies, most importantly tap-jira.
Old Github actions were also updated.
=> Prepare a release for version 0.63.0

CHANGELOG.md, setup.py
Release 0.64.0
https://transferwise.atlassian.net/browse/AP-1772
=> Prepare for Release 0.64.0

README.md, dev-project/README.md, dev-project/docker-compose.yml, docs/index.rst
[AP-1765](https://transferwise.atlassian.net/browse/AP-1765)
[AP-1765]: https://transferwise.atlassian.net/browse/AP-1765?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Announce PipelineWise structure change

CHANGELOG.md, setup.py
Release 0.64.1
https://transferwise.atlassian.net/browse/AP-1800
=> prepare for release 0.64.1

CHANGELOG.md, pipelinewise/cli/schemas/config.json, setup.py
Prepare for release 0.69.0 which contains of reset_state command for MySQL taps
=> [release/0.69.0] Release 0.69.0 reset_state command for mysql taps

singer-connectors/tap-snowflake/setup.py
Bumps `snowflake-connector-python` version in `tap-snowflake` to address dependency version conflicts. 
Internal ticket: https://transferwise.atlassian.net/browse/AP-2180
=> Bump Snowflake Connector to 3.15.X release

CHANGELOG.md, setup.py
Includes changes from https://github.com/transferwise/pipelinewise/pull/1214
=> Release/0.69.2 - Bump Snowflake Connector 

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/e2e_tests.yml
https://transferwise.atlassian.net/browse/AP-2212
=> [AP-2212] increased timeout to 6 minutes for e2e tests

setup.py, singer-connectors/target-postgres/setup.py
https://transferwise.atlassian.net/browse/AP-2221
=> [AP-2221] bump psycopg2-binary from 2.9.5 to 2.9.10

CHANGELOG.md, setup.py
Prepare for release 0.70.0
- Replace pkg_resource with importlib.metadata
- Increase timeout to 6 minutes for e2e tests
- bump psycopg2-binary from 2.9.5 to 2.9.10
=> Prepare for release 0.70.0

CHANGELOG.md, setup.py
https://transferwise.atlassian.net/browse/AP-2274
=> Prepare for release 0.72.0

Dockerfile.barebone
https://transferwise.atlassian.net/browse/AP-2301
=> [AP-2301] bump py in barebone from `3.8` to `3.10`

CHANGELOG.md, setup.py
https://transferwise.atlassian.net/browse/AP-2302
=> prepare for release 0.72.1

CHANGELOG.md, Dockerfile, Dockerfile.barebone, setup.py
prepare for release 0.72.2 and using `python:3.10-slim-bullseye` in Dockerfile and Dockerfile.barebone
https://transferwise.atlassian.net/browse/AP-2302
=> prepare for release 0.72.2

singer-connectors/tap-twilio/tap_twilio/streams.py
[HANDL-9246]
Pagination was not working correctly for call_summaries. Fixing bookmarks, adding max days ago: 30.
[HANDL-9246]: https://transferwise.atlassian.net/browse/HANDL-9246?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [HANDL-9246] Fix pagination in tap-twilio call summaries

CHANGELOG.md, setup.py
https://transferwise.atlassian.net/browse/AP-2337
=> [AP-2337] prepare for new release 0.73.0

dev-project/docker-compose.yml, dev-project/pg/Dockerfile
- The Debnezium Docker Hub image registry is deprecated. Switches to the Quay.io registry to get a newer version of the base Alpine image. 
- Adjust dependency installation to update apk 
- Switch to `clang19`, which is required by dependencies 
https://transferwise.atlassian.net/browse/AP-2445
=> AP-2445: Fix CI failures in Snowflake integration tests
