transferwise/pipelinewise

- bin/pipelinewise-docker
The script uses specific bash constructions, like `[[ $# -gt 0 ]]`, which don't work in other shells like zsh. With this change, we specify that this script needs bash to run, so it works on zsh and others.
> Use bash instead of sh on pipelinewise-docker

- .dockerignore
- dev-project/.virtualenvs/README.md
- dev-project/docker-compose.yml
Minor improvements on dev-project:
- Don't use `.virtualenvs` directories from host to make install script running faster in container
- Adds `dev-project` to `.dockerignore` to exclude it from the executable docker image
> Dev project enhancements

- pipelinewise/fastsync/commons/target_postgres.py
- pipelinewise/fastsync/commons/target_redshift.py
- pipelinewise/fastsync/commons/target_snowflake.py
- pipelinewise/fastsync/commons/utils.py
- pipelinewise/fastsync/mysql_to_redshift.py
- pipelinewise/fastsync/mysql_to_snowflake.py
- pipelinewise/fastsync/postgres_to_redshift.py
- pipelinewise/fastsync/postgres_to_snowflake.py
- singer-connectors/target-postgres/requirements.txt
- tests/end-to-end/test-project/tap_mysql.yml.template
- tests/end-to-end/test-project/tap_postgres.yml.template
- tests/end-to-end/test_e2e.py
- tests/units/fastsync/commons/test_fastsync_utils.py
This PR is for FastSync Redshift compatibility to grant access to users and groups separately. Original issue reported at: https://github.com/transferwise/pipelinewise-target-redshift/issues/15
YAML can be defined in this format as well:
```
schemas:
- source_schema: "my_db"             # Source schema (aka. database)
target_schema: "repl_my_db"        # Target schema in the destination Data Warehouse
target_schema_select_permissions:  # Optional only for Redshift
users: ["user1", "user2]
groups: ["group1", "group2"]
```
This is only for AWS Redshift. Other supported target databases (snowflake and postgres) can still use the list of roles as earlier.
> Adds option to grant user/groups separately in Redshift

- pipelinewise/cli/utils.py
Upon discovering that tap-s3-csv (And possibly other taps) emits state messages with only `bookmarks`, which results in the state file not being updated due to these messages failing validation. To solve this, I dropped `currently_syncing` key from the validation and only relied on messages being json objects and existence of `bookmarks` key.
> Drop currently_syncing key from state message validation

- pipelinewise/cli/__init__.py
- pipelinewise/cli/pipelinewise.py
- tests/units/cli/cli_args.py
Extra option to get tap-run and fastsync log output into std-out (#222 ).
I run PipelineWise Docker with Airflow (_DockerOperator_) and I need this option to see all the logs into Airflow.
> Add extra_log parameter to CLI

- pipelinewise/fastsync/commons/tap_mysql.py
Logging now looks like:
```
Exporting batch from 0 to 20000 rows from adventureworks.salesorderheader...
Exported total of 31465 rows from adventureworks.salesorderheader...
```
> Addressing enchancement #251. Logging on row counts is more descriptive and accurate

- pipelinewise/fastsync/mysql_to_snowflake.py
Fixed an issue when cached `information_schema.columns` table was not refreshed when mysql-to-snowflake FastSync completed.
> mysql-to-snowflake fastsync: refresh information_schema columns cache

- setup.py
- singer-connectors/tap-postgres/requirements.txt
- singer-connectors/target-snowflake/requirements.txt
- tests/end-to-end/test_e2e.py
**PROBLEM**
`snowflake-python-connector` was causing some dependency issues and circleci was failing:
```
tests/end-to-end/test_e2e.py:175: … AssertionError: assert not 'STDOUT: 2019-11-01 08:47:33 INFO: Running postgres_source_sf tap in snowflake…`
```
**REASON**
Massive dependency hell across `boto3`,`botocore`, `snowflake-python-connector` (latest 2.0.3), `azure-storage-python`, `python-dateutil` and `urllib`:
Running the target-snowflake tests programatically (locally and circleci) is fine but running `target-snowflake` executable from the command line (like pipelinewise does) was generating the error at install time:
```  
ERROR: botocore 1.13.9 has requirement python-dateutil<2.8.1,>=2.1; python_version >= "2.7", but you'll have python-dateutil 2.8.1 which is incompatible.
ERROR: …
```
> Fix dependency hell

- pipelinewise/cli/pipelinewise.py
- tests/units/cli/resources/test_post_import_checks/tap_properties_with_no_pk_full_table.json
- tests/units/cli/resources/test_post_import_checks/tap_properties_with_no_pk_incremental.json
- tests/units/cli/resources/test_post_import_checks/tap_properties_with_no_pk_log_based.json
- tests/units/cli/resources/test_post_import_checks/tap_properties_with_no_pk_not_selected.json
- tests/units/cli/resources/test_post_import_checks/tap_properties_with_pk.json
- tests/units/cli/resources/test_post_import_checks/target_config_pk_not_required.json
- tests/units/cli/resources/test_post_import_checks/target_config_pk_required.json
- tests/units/cli/test_cli.py
Checking if primary key exists in the source table at YAML import time. In this case we are noticed earlier if source table is not configured correct and don't need to wait the first run of the tap when it's failing.
Output in case of no Primary Key in a table:
```
-------------------------------------------------------
IMPORTING YAML CONFIGS FINISHED
-------------------------------------------------------
Total targets to import        : 3
Total taps to import           : 132
Taps imported successfully     : 132
Taps failed to import          : [No primary key set for - LOG_BASED source_db-table_one]
Runtime                        : 0:02:34.801859
-------------------------------------------------------
```
If `primary_key_required: False` set in tap YAML then check passes even if no PK …
> Add post import checks to detect tables with no primary key

- singer-connectors/target-redshift/requirements.txt
Bump target-redshift to 1.1.0 to have everything target-snowflake has:
* Emit new state message as soon as data flushed to Redshift
* Add `flush_all_streams` option
* Add `max_parallelism` option
> bump target-redshift

- .circleci/config.yml
- Dockerfile
- README.md
- docs/installation_guide/installation.rst
- install.sh
This PR adding the option to install only specific singer connectors from the command line.
Available options:
* `./install.sh` : Installs only the default singer connectors. `DEFAULT` and `EXTRA` connectors specified here at: https://github.com/transferwise/pipelinewise/blob/0662cf0f31703816d37c8d03e44daedb4ef7ae6b/install.sh#L160
* `./install.sh --connectors=all` : Finds and installs every available singer connectors automatically
* `./install.sh --connectors=tap-mysql,tap-postgres,target-snowflake` : Installs only a specific list of singer connectors
* `./install.sh --clean` : Clean and delete every previously installed component from the system
> Selectively install singer connectors

- pipelinewise/cli/pipelinewise.py
- tests/units/cli/resources/test_post_import_checks/target_config_pk_not_defined.json
- tests/units/cli/test_cli.py
**Description**
If `primary_key_required` key not defined explicitly in the target YAML then `post_import_tap_checks` not reporting that source table has no PK.
**Reason**
`primary_key_required` is an optional parameter in the target YAMLs and defaults to `True` but `_run_post_import_tap_checks` expecting the default as `False`. This PR makes it to be in sync and adding some new tests to cover the scenario when `primary_key_required` is not explicitly defined in the target YAML.
> fixed issue when missing required PK not detected by post_import_tap_checks

- .circleci/config.yml
- dev-project/pipelinewise-config/tap_mysql_mariadb.yml
- pipelinewise/fastsync/commons/tap_mysql.py
- pipelinewise/fastsync/commons/target_snowflake.py
- pipelinewise/fastsync/mysql_to_snowflake.py
- singer-connectors/tap-mysql/requirements.txt
- singer-connectors/target-snowflake/requirements.txt
- tests/db/tap_mysql_data.sql
- tests/end-to-end/test-project/tap_mysql_to_sf.yml.template
- tests/end-to-end/test_e2e.py
Supporting binary and varbinary columns in Mysql sources when using fast sync.
Atm, I'm fetching the right pipelinewise-tap-mysql and pipelinewise-target-snowflake using git urls because the latest changes are not yet released on PyPi. I will update this PR once those changes are released, so this PR shouldn't be merged until then.
Last change to finish AP-111.
TODO before merge:
1- Update requirements files of pipelinewise-tap-mysql & pipelinewise-target-snowflake connectors.
2- bump pipelinewise minor
> support binary and varbinary columns in Mysql to SF fastsync

- pipelinewise/cli/tap_properties.py
Data flattening needs to be disabled by default since we upgraded to pipelinewise-tap-kafka 2.0.0 . The latest tap-kafka doesn't do data flattening at all.
> Disable data flattening for kafka by default

- pipelinewise/cli/pipelinewise.py
Fixing #289 
**Description**
`discover_tap` command crashes with every tap and target. To reproduce run:
`pipelinewise discover_tap --tap test_mysql_mysql_mariadb --target my_test_snowflake`
**Exception**
`
Traceback (most recent call last): File "/app/.virtualenvs/pipelinewise/bin/pipelinewise", line 11, in <module> load_entry_point('pipelinewise', 'console_scripts', 'pipelinewise')() File "/app/pipelinewise/cli/__init__.py", line 109, in main getattr(pipelinewise, args.command)() File "/app/pipelinewise/cli/pipelinewise.py", line 630, in discover_tap post_import_errors = self._run_post_import_tap_checks(schema_with_diff, target) File "/app/pipelinewise/cli/pipelinewise.py", line 1229, in _run_post_import_tap_checks primary_key_required = target.get("primary_key_required", False) …
> Fixed discovery mode

- pipelinewise/cli/pipelinewise.py
Small PR to make post import error messages more understandable. The current format of a post impor check failure is:
```
Post import tap checks failed at <TAP_ID>. ['No primary key set for - <REPLICATIONA_METHOD> <TAP_STREAM_ID>.
```
With this PR it's going to look like:
```
Post import tap checks failed at <TAP_ID>: No primary key set for <TAP-STREAM_ID> stream (<REPLICATION_METHOD>)
```
> [AP-454] More meaningful post import check message

- pipelinewise/cli/config.py
- pipelinewise/cli/pipelinewise.py
- pipelinewise/cli/schemas/target.json
- pipelinewise/cli/utils.py
- pipelinewise/fastsync/commons/utils.py
- pipelinewise/fastsync/mysql_to_redshift.py
- pipelinewise/fastsync/mysql_to_snowflake.py
- pipelinewise/fastsync/postgres_to_redshift.py
- pipelinewise/fastsync/postgres_to_snowflake.py
- pipelinewise/fastsync/s3_csv_to_snowflake.py
- singer-connectors/target-snowflake/requirements.txt
- tests/units/cli/test_cli_utils.py
- tests/units/cli/test_config.py
- tests/units/fastsync/test_s3_csv_to_snowflake.py
Currently every temp file created in the system `/tmp` directory but we'd like to have a pipelinewise specific temp directory in `~/.pipelinewise/tmp` to isolate pipelinewise temp files from system temp files. This PR makes it.
Temp files in scope:
* Fastsync `.csv.gz` files
* Generated runtime `config.json` files to run taps
* The modified `pipelinewise/cli/schemas/target.json` JSON schema makes sure no target allowed to create with the name `tmp`. This check runs automatically by `validate` and `import` commands and from circeci as well.
* The generated target `config.json` automatically includes a new `temp_dir` property so every target can write their temp files into the same directory.
> [AP-415] Create pipelinewise specific common temp directory

- docs/connectors/taps/kafka.rst
- pipelinewise/cli/samples/tap_kafka.yml.sample
pipelinewise-tap-kafka 2.0.0 changed the structure of kafka YAML file. This PR updates the documentation and the sample yaml file according to the changes in tap-kafka 2.0.0.
> [AP-329] Update doc and samples to fit tap-kafka 2.0.0

- docs/user_guide/cli.rst
- pipelinewise/cli/__init__.py
- pipelinewise/cli/pipelinewise.py
- setup.py
- tests/units/cli/test_cli.py
This PR adds **stop_tap** command to PipelineWise. Usage: `pipelinewise stop_tap --target <TARGET_ID> --tap <TAP_ID>`
At the moment we need to stop long running taps manually by `kill -9 <PID>`.
This PR creates a pidfile for every running tap in `~/.pipelinewise/<target_id>/<tap_id>/pipelinewise.pid` so **stop_tap** can detect quickly the process id and can send SIGINT to the process that triggers a graceful exit.
This will also allow us detecting if the tap is in running status much quicker as we do today. Currently we check the log history to find if the tap is running or not. In case of 150 taps the startup process takes at least 1 minute for each tap. Doing the same by checking if the pidfile exists is much quicker.
> [AP-421] Add stop_tap command

- singer-connectors/tap-mysql/requirements.txt
- tests/db/tap_mysql_db.sh
- tests/end-to-end/e2e_utils.py
- tests/end-to-end/test-project/tap_mysql.yml.template
- tests/end-to-end/test_e2e.py
This PR makes mariadb to postgres end to end tests more granular. The primary goal of this PR is making sure that performance improvements in pipelinewise-tap-mysql [here](https://github.com/transferwise/pipelinewise-tap-mysql/pull/12) is not introducing new bug.
This PR also refactors the existing end to end tests structure and eliminates some duplicates by introducing `e2e_utils.py` and move common functions to this file.
> [AP-483] Add more granular end to end tests

- singer-connectors/tap-jira/requirements.txt
Bump to tap-jira to 2.0.0
Due to an API change in Jira, `tap-jira` cannot extract the users streams. This has been fixed in https://github.com/singer-io/tap-jira/pull/46 and released in tap-jira-2.0.0.
> [AP-XXXX] Bump tap-jira

- pipelinewise/fastsync/commons/tap_mysql.py
- tests/db/tap_mysql_data.sql
- tests/end_to_end/test-project/tap_mysql_to_sf.yml.template
- tests/end_to_end/test_e2e.py
Sanitize columns during FstSync Mysql to SF.
Table in MYSQL:
```
CREATE TABLE `edgydata` (
`order` int(11) PRIMARY KEY AUTO_INCREMENT,
`c_varchar` varchar(128),
`group` int,
`case` varchar(1)
) ENGINE=MyISAM AUTO_INCREMENT=1001 DEFAULT CHARSET=utf8;
INSERT INTO `edgydata` VALUES
(1, 'Lorem ipsum dolor sit amet', 10, 'A'),
(2, 'Thai: แผ่นดินฮั่นเสื่อมโทรมแสนสังเวช', 20, 'A'),
(3, 'Chinese: 和毛泽东 <<重上井冈山>>. 严永欣, 一九八八年.', null, 'B'),
(4, 'Special Characters: ["\\,''!@£$%^&*()]\\\\', null, 'B'),
(5, '	', 20, 'B'),
(6,'Enter	The
Ninja', 10, 'A'),
(7,'Liewe
Maatjies', 20, 'A'),
(8,'Liewe	Maatjies', 10, null
```
with a config like this:
```
- table_name: "edgydata" # This table has SF reserved words as columns
replication_method: "LOG_BASED"
transformations:
- column: "case"
type: "HASH"
```
The …
> [AP-453] handle reserved words used for column names in FS mysql to SF

- pipelinewise/cli/pipelinewise.py
- pipelinewise/fastsync/commons/tap_postgres.py
- pipelinewise/fastsync/commons/target_snowflake.py
- singer-connectors/target-snowflake/requirements.txt
- tests/db/tap_postgres_data.sql
- tests/end_to_end/test-project/tap_postgres_to_sf.yml.template
Supporting reserved words as table names when syncing from PG to SF, this includes PG reserved words used as table names in PG DB and SF reserved words used as table names.
Source table:
```
DROP TABLE IF EXISTS "ORDER" CASCADE;
CREATE TABLE "ORDER"
(
id serial primary key,
cvarchar varchar,
created_at timestamp default current_timestamp
);
insert into "ORDER" (cvarchar) values ('A'), ('B'), ('C'), ('D'), ('E'), ('F'), ('G');
```
Replication config
```
- table_name: "order"
replication_method: "INCREMENTAL"
replication_key: "created_at"
transformations:
- column: 'cvarchar'
type: 'MASK-HIDDEN'
```
Table in SF
> [AP-549] Support reserved words as table names

- install.sh
The install scripts showing components incorrectly, and there is a line in the list with no package name `1.1.0`:
```
--------------------------------------------------------------------------
Installed components:
--------------------------------------------------------------------------
Component            Version
-------------------- -------
pipelinewise         0.13.3
1.1.0
tap-adwords          1.11.2
tap-jira             2.0.0
tap-kafka            2.1.0
tap-mysql            1.2.0
tap-oracle           1.0.0
tap-postgres         1.4.1
tap-s3-csv           1.1.0
tap-salesforce       1.1.0
tap-snowflake        1.1.0
tap-zendesk          1.1.0
target-postgres      1.1.0
target-redshift      1.3.0
target-s3-csv        1.2.0
target-snowflake     1.5.0
transform-field      1.2.0
```
This is …
> [AP-590] Fix install script to search full names packages

- singer-connectors/tap-postgres/requirements.txt
Bump pipelinewise-tap-postgres to 1.5.2
> Bump pipelinewise-tap-postgres to 1.5.2

- pipelinewise/fastsync/commons/target_snowflake.py
- pipelinewise/fastsync/mysql_to_snowflake.py
- pipelinewise/fastsync/postgres_to_snowflake.py
- pipelinewise/fastsync/s3_csv_to_snowflake.py
- singer-connectors/target-snowflake/requirements.txt
- tests/units/fastsync/test_s3_csv_to_snowflake.py
This PR is getting rid of `PIPELINEWISE.COLUMNS` table and its caching mechanism in fastsync components to snowflake. This is the corresponding PR of https://github.com/transferwise/pipelinewise-target-snowflake/pull/67 
Build and CircleCI tests supposed to fail until pipelinewise-target-snowflake_1.6.1 not released to PyPI
> [AP-591] Not creating PIPELINEWISE.COLUMNS cache table

- install.sh
This reverts commit 2ef9f22e
pipelinewise command is unavailable in docker container.
> Revert "generate safe requirements with no conflicts"

- pipelinewise/fastsync/commons/tap_mysql.py
Increasing default `export_batch_rows` size from 20k to 50k in fastsync from mysql.
> [AP-XXXX] Increase default export batch size

- pipelinewise/cli/config.py
- pipelinewise/cli/pipelinewise.py
- pipelinewise/cli/utils.py
- tests/units/cli/resources/test_invalid_yaml_config_with_duplicate_targets/tap_test_unknown_target.yml
- tests/units/cli/resources/test_invalid_yaml_config_with_duplicate_targets/target_test.yaml
- tests/units/cli/resources/test_invalid_yaml_config_with_duplicate_targets/target_test.yml
- tests/units/cli/resources/test_validate_command/test_yaml_config_two_targets/tap_test.yml
- tests/units/cli/resources/test_validate_command/test_yaml_config_two_targets/target_test.yaml
- tests/units/cli/resources/test_validate_command/test_yaml_config_two_targets/target_test.yml
- tests/units/cli/test_cli.py
- tests/units/cli/test_cli_utils.py
- tests/units/cli/test_config.py
- Support tap/target config files with `.yaml` extension when importing config.
- Raise exception when +2 taps have same ID, same for targets when importing and validating taps and targets.
> [AP-529] Support .yaml extension and prevent duplicate IDs

- pipelinewise/cli/config.py
- tests/units/cli/test_config.py
add_metadata_columns doesn't seem to be defined by default when building the tap inheritable_config.json file. Making it harder to configure it later inside a tap .yml configuration.
This PR add the value inside the tap_inheritable_config dictionary.
<< Write here the description of your PR. Without description won't be approved! >>
> add_metadata_columns is not defined in inheritable_config

- pipelinewise/fastsync/commons/target_snowflake.py
- pipelinewise/fastsync/mysql_to_snowflake.py
- pipelinewise/fastsync/postgres_to_snowflake.py
- pipelinewise/fastsync/s3_csv_to_snowflake.py
Support for AWS iam roles for snowflake fastsync.
Creating the boto3 client object without acces/secret keys will enable boto3 to look for all possible credentials . Creating the storage integration object in snowflake with necessary permission for the bucket will enable load data to snowflake to work without aws credentials
> Support for iam roles for snowflake fastsync

- pipelinewise/cli/config.py
- pipelinewise/cli/tap_properties.py
- pipelinewise/cli/utils.py
- tests/units/cli/resources/tap-valid-kafka.yml
- tests/units/cli/test_cli_utils.py
This PR adds `local_store_dir` config parameter automatically to every generated kafka tap configuration (json) and pointing to the pipelinewise temp directory. Defaults: `~/.pipelinewise/tmp`
**Background**
Starting from `pipelinewise-tap-kafka` 3.0.0, the consumed data from Kafka is loading into a local storage first and the path of this local storage is configurable in the tap json by the `local_store_dir` key. Further details about the local storage mechanism at [here](https://github.com/transferwise/pipelinewise-tap-kafka/pull/16).
> [AP-630] Add local_store_dir automatically to kafka tap configs

- docs/connectors/taps/snowflake.rst
- pipelinewise/cli/tap_properties.py
- tests/units/cli/resources/tap-valid-snowflake.yml
- tests/units/cli/test_cli_utils.py
This PR generating the mandatory `tables` parameter to tap-snowflake type of taps by parsing the YAML file. This is required since tap-snowflake introducing the mandatory `tables` configuration parameter in https://github.com/transferwise/pipelinewise-tap-snowflake/pull/19
> [AP-635] Generate tables config parameter for tap-snowflake

- docs/connectors/targets/redshift.rst
- pipelinewise/cli/samples/target_redshift.yml.sample
- pipelinewise/fastsync/commons/target_redshift.py
- pipelinewise/fastsync/mysql_to_redshift.py
- pipelinewise/fastsync/postgres_to_redshift.py
Merge missing functionalites from target-redshift to redshift fastsync:
* `aws_session_token`: AWS STS token for temporary credentials
* `aws_redshift_copy_role_arn`: AWS Role ARN to be used for the Redshift COPY operation
Addresses issue reported at https://github.com/transferwise/pipelinewise-target-redshift/pull/31#issuecomment-561770332
> [AP-XXXX] Support for iam roles and env vars for redshift fastsync

- pipelinewise/fastsync/commons/tap_mysql.py
- pipelinewise/fastsync/commons/target_snowflake.py
- tests/db/tap_mysql_data.sql
- tests/db/tap_postgres_data.sql
- tests/end_to_end/test-project/tap_mysql_to_sf.yml.template
- tests/end_to_end/test-project/tap_postgres_to_sf.yml.template
This PR fixes an issue when fastsync to snowflake fails on tables with space in the table name. This happens when generating `MERGE` and `COPY` commands and when detecting primary keys in mysql tables.
There are some related PRs that is not fastsync related, but fixing the same issues with spaces in table names:
* https://github.com/transferwise/pipelinewise-tap-postgres/commit/58107197e0c62004532850dbc31e43963039c2af
* https://github.com/transferwise/pipelinewise-target-snowflake/commit/af5a3260169464a8323a9d35e0426c20347d1dff
> [AP-659] Fix Fastsync to Snowflake with space in the table name

- pipelinewise/cli/tap_properties.py
- pipelinewise/fastsync/commons/tap_postgres.py
- pipelinewise/fastsync/postgres_to_snowflake.py
- tests/units/fastsync/commons/test_fastsync_tap_postgres.py
This PR makes possible to `LOG_BASE` replicate multiple database in the same postgres instance by multiple parallel running taps:
* Replication slot name includes the tap_id using the pattern: `pipelinewise_<dbname>_<tap_id>`
* Passing `tap_id` to tap-postgres so it can locate and use it to consume new wal entries
* Backward compatibility with `PPW <= 0.15.x` to use the old replication slot pattern if exists. 
Related PR for tap-postgres: https://github.com/transferwise/pipelinewise-tap-postgres/pull/50
> [AP-655] Create unique replication slots for PG fastsync

- pipelinewise/fastsync/commons/target_postgres.py
- tests/units/fastsync/commons/test_fastsync_target_postgres.py
Target-Postgres common fastsync component is currently not working and not used anywhere. This PR makes it to work.
This change is an improvement to use target-postgres and fastsync-postgres components to speed up developing complex end to end test cases locally so we don't need to rely on external commercial databases like Snowflake or Redshift.
The new E2E test cases are WiP and will be transferrable between different target components. When newly added E2E tests will be working with local target-postgres we can transfer them easily to snowflake or other target connectors.
> [AP-678] Make common fastsync target-postgres to work

- pipelinewise/fastsync/commons/tap_mysql.py
- pipelinewise/fastsync/commons/tap_postgres.py
- pipelinewise/fastsync/commons/tap_s3_csv.py
- pipelinewise/fastsync/commons/target_postgres.py
- pipelinewise/fastsync/commons/target_snowflake.py
- singer-connectors/target-postgres/requirements.txt
- tests/units/fastsync/commons/test_fastsync_target_postgres.py
- tests/units/fastsync/commons/test_fastsync_target_snowflake.py
- tests/units/fastsync/test_fastsync_tap_s3_csv.py
`CREATE TABLE` statements not generated correctly by fastsync if table has composite key. The only reason why fastsync is still working with tables with composite PKs is that Snowflake and Redshift don't enforce primary keys.
Fixing it to generate DDLs with composite PKs correctly.
> [AP-680] Fastsync tables with composite primary key

- install.sh
- pipelinewise/cli/pipelinewise.py
- pipelinewise/fastsync/mysql_to_postgres.py
- pipelinewise/fastsync/postgres_to_postgres.py
- setup.py
- tests/end_to_end/test_target_postgres.py
This PR adds `mysql-to-postgres` and `postgres-to-postgres` fastsync components.
Related PR: https://github.com/transferwise/pipelinewise/pull/398
This change is an improvement to use target-postgres and fastsync-postgres components to speed up developing complex end to end test cases locally so we don't need to rely on external commercial databases like Snowflake or Redshift.
The new E2E test cases are WiP and will be transferrable between different target components. When newly added E2E tests will be working with local target-postgres we can transfer them easily to snowflake or other target connectors.
E2E test cases require some refactoring in the mysq and postgres input dataset. That will be sent in a new PR.
> [AP-678] Add fastync mysql-to-pg and pg-to-pg

- pipelinewise/fastsync/commons/target_postgres.py
- pipelinewise/fastsync/mysql_to_postgres.py
- pipelinewise/fastsync/postgres_to_postgres.py
Fix postgres-to-postgres and mysql-to-postgres fastsync compoents to create target schemas sequentially before syncing tables in parallel. This is to avoid a concurrency issues becase Postgres requires a complex locking mechanism for `CREATE SCHEMA IF NOT EXISTS` to run in parallel.
Tests included in PR https://github.com/transferwise/pipelinewise/pull/403
> [AP-645] Create target schemas sequentially

- dev-project/.env
- tests/end_to_end/helpers/env.py
- tests/end_to_end/test-project/tap_s3_csv_to_pg.yml.template
- tests/end_to_end/test-project/tap_s3_csv_to_rs.yml.template
- tests/end_to_end/test-project/tap_s3_csv_to_sf.yml.template
- tests/end_to_end/test_target_snowflake.py
End to end tests expect test files on s3 to test tap_s3_csv. These files currently uploaded to s3 manually. This PR uploads the files automatically every time when the tests starting.
> [AP-692] Upload tap_s3_csv test input files to s3 automatically

- pipelinewise/fastsync/commons/target_redshift.py
- pipelinewise/fastsync/mysql_to_redshift.py
- pipelinewise/fastsync/postgres_to_redshift.py
- singer-connectors/target-redshift/requirements.txt
- tests/end_to_end/helpers/assertions.py
- tests/end_to_end/helpers/db.py
- tests/end_to_end/helpers/env.py
- tests/end_to_end/test-project/tap_postgres_to_rs.yml.template
- tests/end_to_end/test_target_redshift.py
This PR syncs the target_snowflake fastsync functionalities to target_redshift and adds support to use reserved words as table and column names in Redshift.
It also syncs the end to end test cases. Since we have common test data and end-to-end test functions, the test cases in target_snowflake can run on target_redshift and target_postgres as well.
> [AP-645] Support reserved words as table and column names in Redshift

- pipelinewise/fastsync/commons/tap_s3_csv.py
- pipelinewise/fastsync/commons/target_postgres.py
- pipelinewise/fastsync/s3_csv_to_postgres.py
- setup.py
- tests/end_to_end/helpers/db.py
- tests/end_to_end/test_target_postgres.py
Add Fastsync from `tap_s3_csv` to `target_postgres`
Including all the end to end tests from the existing fastsync `s3_csv_to_snowflake`
> [AP-XXXX] Add Fastsync s3_csv to postgres

- pipelinewise/fastsync/mysql_to_postgres.py
- pipelinewise/fastsync/mysql_to_redshift.py
- pipelinewise/fastsync/mysql_to_snowflake.py
- pipelinewise/fastsync/postgres_to_postgres.py
- pipelinewise/fastsync/postgres_to_redshift.py
- pipelinewise/fastsync/postgres_to_snowflake.py
- tests/units/fastsync/assertions.py
- tests/units/fastsync/commons/test_fastsync_tap_s3_csv.py
- tests/units/fastsync/test_mysql_to_postgres.py
- tests/units/fastsync/test_mysql_to_redshift.py
- tests/units/fastsync/test_mysql_to_snowflake.py
- tests/units/fastsync/test_postgres_to_postgres.py
- tests/units/fastsync/test_postgres_to_redshift.py
- tests/units/fastsync/test_postgres_to_snowflake.py
- tests/units/fastsync/test_s3_csv_to_postgres.py
This PR adds unit tests for every fastsync component by reusing the existing `s3-csv-to-snowflake.py`.
Some minor refactoring applied in some fastsync components as well. This allows to reuse the existing test cases and it gives the same behaviour to every fastsync executable.
The fastsync components and unit tests are very similar. Would be great removing the duplicates in the fastsync executables by creating base class for common fastsync functionalities. This exercise is not part of this PR.
> [AP-694] Add unit tests for fastsync components

- dev-project/pipelinewise-config/tap_postgres_logical.yml
- tests/end_to_end/test-project/tap_postgres_to_pg.yml.template
- tests/end_to_end/test-project/tap_postgres_to_rs.yml.template
- tests/end_to_end/test-project/tap_postgres_to_sf.yml.template
Decrease timeout of tap-postgres logical example to set-up for better testing.
Currently, automatically testing LOG_BASED is difficult due to this excessive timeout.
> Decrease timeout to set-up for better testing

- docs/connectors/taps/mysql.rst
- pipelinewise/fastsync/commons/tap_mysql.py
- singer-connectors/tap-mysql/requirements.txt
- tests/units/fastsync/commons/test_fastsync_tap_mysql.py
This PR is getting an optional `session_sqls` parameter from the connection config and running each of them automatically right after the mysql/mariadb connection has made.
Using this approach we don't hardcode session parameters, every tap can have different values and we support different different session parameter names used by the different version of mariadb/mysql.
```
id: "tap_id"
name: "Example Tap"
type: "tap-mysql"
owner: "someone"
sync_period: "*/5 * * * *"
db_conn:
host: "localhost"
port: 3306
user: my_user
password: secret
dbname: "my_db"
session_sqls:
- SET SESSION max_statement_time=0
- SET SESSION wait_timeout=28800
- ... some more SQL ...
``` 
This PR is inline with https://github.com/transferwise/pipelinewise-tap-mysql/pull/19
> [AP-372] Add optional session_sqls connection parameter

- pipelinewise/fastsync/mysql_to_postgres.py
- pipelinewise/fastsync/mysql_to_redshift.py
- pipelinewise/fastsync/mysql_to_snowflake.py
- singer-connectors/tap-postgres/requirements.txt
- tests/db/tap_mysql_data.sql
- tests/end_to_end/test_target_postgres.py
- tests/end_to_end/test_target_redshift.py
- tests/end_to_end/test_target_snowflake.py
Fixed an issue when JSON type columns not loaded correctly into target databases.
The PR bumps `pipelinewise-tap-postgres` to 1.6.2 to include the main fix and extending the end to end tests suite to load JSON data from tap-mysql, tap-postgres to target-snowfake, target-postgres and target-redshift.
> [AP-700] Fixed an issue when JSON type columns not loaded correctly

- singer-connectors/target-snowflake/requirements.txt
This PR is to include "Fix loading tables with space in the name", added by https://github.com/transferwise/pipelinewise-target-snowflake/commit/af5a3260169464a8323a9d35e0426c20347d1dff
> [AP-659] Bump pipelinewise-target-snowflake

- .circleci/config.yml
- Dockerfile
This PR is a minor improvement to bump the docker images from 3.7.4 to the latest 3.7.7.
At the same time it's switching to use the python **slim** buster image when running PPW from 
Docker. The slimified python image removing extra files that are normally not necessary within containers, such as man pages and documentation, resulting a much smaller image size but keeping the same runtime libraries.
> [AP-XXXX] Bump python docker base images

- install.sh
Circleci on master is currently failing when it's building and publishing the Docker image. Seems like the reason is a syntax error when trying to install the connectors into the image
> [AP-639] Fix install script

- dev-project/pipelinewise-config/target_postgres.yml
`target_postgres.yaml` in the dev project is currently using a wrong port number and manual PPW commands when working with target_postgres in the dev env currently gives error messages. This PR fixing it.
The port number accidentally changed by PR #403. Unit and end-to-end tests are not affected, e2e tests using different, dynamically generated YAML files, hence circleci didn't detect the wrong config.
> Fix target-postgres port number in dev env

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
- README.md
PipelineWise needs code contribution guide for the community.
The PR includes:
* New contribution guide
* New issue template
* Updated PR template
* Updated Readme
> [AP-716] Add code contribution guide

- pipelinewise/cli/schemas/tap.json
- tests/units/cli/resources/test_invalid_tap_mongo_yaml_config/tap_test_invalid_replication_method.yml
- tests/units/cli/resources/test_invalid_tap_mongo_yaml_config/target_test.yml
- tests/units/cli/test_config.py
Disable the incremental method with the help of the validation against json schema.
Given that the we can only use Draft4 valid schema currently, I went with the implication pattern to put a condition on the replication methods that can be used for tap_mongodb. 
PS: Example of [the implication pattern](https://stackoverflow.com/questions/51203606/jsonschema-attribute-conditionally-required-depends-on-parent-object?noredirect=1&lq=1).
> [AP-689] Disable incremental for tap_mongodb

- .circleci/config.yml
- dev-project/entrypoint.sh
- tests/db/target_postgres.sh
- tests/db/target_postgres_data.sql
This PR creates the `pgcrypto` extension automatically in the dev env postgres target database.
Using `target_postgres` in the dev environment gives `ERROR: function digest(unknown, unknown) does not exist`, when do fast-sync on a table with SHA transformations.
This is because the `DIGEST` function exists in the pgcrypto extension that is not installed by default in the postgres container.
Install `pgcrypto` extensions automatically when starting the dev env.
> Create pgcrypto extension in dev env postgres target

- dev-project/pipelinewise-config/tap_mongodb_to_pg.yaml
tap_mongo in dev env loading into a schema called `mongodb_sync`. This works fine but maybe can consider to keep the naming in sync with other tap target schemas:
* `ppw_dev_tap_mysql`
* `ppw_dev_tap_postgres`
* `ppw_e2e_tap_mysql`
* `ppw_e2e_tap_postgres`
* `ppw_e2e_tap_mongodb` <- this is already in sync with the current naming convention
Following the naming convention above tap_mongo target schema in the dev env renamed to `ppw_dev_tap_mongodb`
> Rename dev project tap mongo target schema

- docs/connectors/targets/snowflake.rst
Target snowflake requires specific permissions which are not clearly documented at https://transferwise.github.io/pipelinewise/connectors/targets/snowflake.html
All the required roles and permissions should be documented.
> [DOC] Update required privileges for target-snowflake

- dev-project/pipelinewise-config/tap_mysql_mariadb.yml
- pipelinewise/fastsync/mysql_to_postgres.py
- pipelinewise/fastsync/mysql_to_redshift.py
- pipelinewise/fastsync/mysql_to_snowflake.py
- tests/db/tap_mysql_data.sql
- tests/end_to_end/helpers/assertions.py
- tests/end_to_end/helpers/db.py
- tests/end_to_end/test-project/tap_mysql_to_pg.yml.template
- tests/end_to_end/test-project/tap_mysql_to_pg_buffered_stream.yml.template
- tests/end_to_end/test-project/tap_mysql_to_rs.yml.template
- tests/end_to_end/test-project/tap_mysql_to_rs_buffered_stream.yml.template
- tests/end_to_end/test-project/tap_mysql_to_sf.yml.template
- tests/end_to_end/test-project/tap_mysql_to_sf_buffered_stream.yml.template
- tests/end_to_end/test_target_postgres.py
- tests/end_to_end/test_target_redshift.py
- tests/end_to_end/test_target_snowflake.py
Fastsync is loading mariadb/mysql `MEDIUMINT` column type into wrong `VARCHAR` column in postgres, snowflake and redshift.
This is incorrect and not in sync with tap-mysql. Due to this issue fastsync first loads the data into a `VARCHAR` column than later singer sends the same column as `INTEGER`. This behaviour results a not necessary column versioning, and the data is loaded into two different columns.
This bug is reported as part of https://github.com/transferwise/pipelinewise/issues/389
1) Fastsync should map mysql/mariadb `MEDIUMINT` to `INTEGER` column types in every fastsync variant.
2) End to end test cases should check column type mappings. This PR extends the assertions.assert_all_columns_exist function to check target data types according to the expected type mapping.
What …
> [AP-772] Fix MySQL MEDIUMINT column type mapping in fastsync

- install.sh
During the latest deployment of PPW, we had an issue with install script not upgrading `pipelinewise-singer-python` to the latest version, that is because we don't delete the existing `.virtualenvs` when deploying, running `pip install` only will not upgrade these non-pinned dependencies.
Dependencies in PipleneWise or in its connectors that are not pinned to a specific version, such as `pipelinewise-singer-python-1.*` need to be upgraded whenever a new version that fits the pattern is present, adding `--upgrade` option will make sure of that.
> [AP-781] Upgrade non-pinned dependencies when new version is available

- docs/connectors/taps/mongodb.rst
- pipelinewise/cli/samples/tap_mongodb.yml.sample
- pipelinewise/fastsync/commons/tap_mongodb.py
- tests/end_to_end/test-project/tap_mongodb_to_pg.yml.template
- tests/end_to_end/test-project/tap_mongodb_to_sf.yml.template
- tests/units/fastsync/commons/test_fastsync_tap_mongodb.py
* Scalability
There is an a memory/scalability issue in this [line](https://github.com/transferwise/pipelinewise/blob/25f16fea25fab8d10eb71be5e7aa4acc2512744c/pipelinewise/fastsync/commons/tap_mongodb.py#L161), if the collection is big, e.g 1.5GB compressed or 25M documents, the statement `export_file.read()` will load all the documents into memory, which either cause a Memory error or take hours if not days for collections of size  30GB compressed just for `bson.decode_iter` to parse the data.
* Logging
There are no logs when a collection is being processed with FastSync which makes it hard to follow/know the progress.
* Scalability
The `bson` library has a function `decode_file_iter` which according to the doc:
> Decode bson data from a file to multiple documents as a generator.
Works …
> [AP-784] Fix FastSync mongoDB

- .circleci/config.yml
- singer-connectors/tap-postgres/requirements.txt
- tests/end_to_end/test-project/tap_postgres_to_pg.yml.template
- tests/end_to_end/test_target_postgres.py
When running tap-postgres `log_based`, new/renamed columns are not detected due the schema in the `properties.json` file being out of date. This results in data loss.
1. At the beginning of every sync, run new discovery of selected streams to get their latest schema representation then send the SCHEMA message to target
2. While doing logical replication, if the WAL payload contains a new column that the stream doesn't know about, refresh the stream schema and send a SCHEMA message to target before the RECORD message.
This should make the target up to date and receive the data in the new/renamed columns.
This change is in [pipelinewise-tap-postgres release v.1.6.3](https://github.com/transferwise/pipelinewise-tap-postgres/releases/tag/v1.6.3) 
What types of changes does your code introduce …
> [AP-803] Fix data loss when syncing from postgres

- docs/connectors/taps/zendesk.rst
- pipelinewise/cli/samples/tap_zendesk.yml.sample
- singer-connectors/tap-zendesk/requirements.txt
`rate_limit`, `max_workers` and `batch_size` tap-zendesk parameters are not configurable.
Bump pipelinewise-tap-zendesk to 1.2.0 that allows the user to configure`rate_limit`, `max_workers` and `batch_size` parameters.
> [AP-XXXX] Bump tap-zendesk to make rate_limit configurable

- pipelinewise/fastsync/commons/tap_mongodb.py
- singer-connectors/tap-mongodb/requirements.txt
- tests/units/fastsync/commons/test_fastsync_tap_mongodb.py
In some cases, for an unknown reason, Mongodb servers generate a resume token that can look like this:
```py
{'_data': '825F167E8C000000322B022C2EC22461E5F6964002E128A18AC0004', '_typeBits': b'\x81\x80'}
```
The unexpected bytes property `_typeBits` causes replication to break as this token is not JSON serializable when saving the state to json file.
*Problematic server*
MongoDB sharded cluster v4.2.2-3
Extract the `_data` hex property only and save it as the token.
Manual test against the problematic server  proved this works, the server can still send in new changes streams with a token that has `_data` only.
Similar change in [pipelinewise-tap-mongodb](https://github.com/transferwise/pipelinewise-tap-mongodb/pull/8)
_Put …
> [AP-810] Resume token not JSON serializable

- pipelinewise/cli/samples/tap_mongodb.yml.sample
- pipelinewise/cli/schemas/tap.json
- singer-connectors/tap-mongodb/requirements.txt
- singer-connectors/tap-mysql/requirements.txt
- tests/end_to_end/test-project/tap_mongodb_to_pg.yml.template
- tests/end_to_end/test-project/tap_mongodb_to_sf.yml.template
- tests/end_to_end/test_target_postgres.py
- tests/end_to_end/test_target_snowflake.py
1. tap-mongodb LOG_BASED has some hardcoded parameters.
2. tap-mysql log_based not detecting new/renamed columns during runtime.
1. Make buffer size and await time configurable, [changes](https://github.com/transferwise/pipelinewise-tap-mongodb/pull/10) in connector. 
2 add check for new columns during log_based and send new schema message to target with up to date schema. [Changes](https://github.com/transferwise/pipelinewise-tap-mysql/pull/27) in connector,
> [AP-814] Integrate tap-mysql and tap-mongodb changes

- singer-connectors/tap-zendesk/requirements.txt
pipelinewise-tap-zendesk does a full refresh on satisfaction_ratings stream.
Bump ppw-tap-zendesk to 1.2.1 which use `start_time` query parameter for satisfaction_ratings stream
> [AP-XXXX] Bump tap-zendesk

- docs/connectors/targets/redshift.rst
- docs/connectors/targets/snowflake.rst
- pipelinewise/cli/schemas/target.json
- pipelinewise/fastsync/commons/target_redshift.py
- pipelinewise/fastsync/commons/target_snowflake.py
- singer-connectors/target-redshift/requirements.txt
- singer-connectors/target-snowflake/requirements.txt
- tests/end_to_end/helpers/env.py
- tests/end_to_end/test-project/target_redshift.yml.template
- tests/end_to_end/test-project/target_snowflake.yml.template
There is no way to update/alter the ACL on an S3 object when uploading (redshift/snowflake).
Allow `s3_acl` to be set in the target's configuration file. This is especially helpful when configuring S3 access through IAM and moving data across aws accounts. For example: `s3_acl: bucket-owner-full-control`.
*Put an `x` in the boxes that apply*
> Support ACL for S3 uploads

- singer-connectors/tap-mysql/requirements.txt
- tests/end_to_end/test_target_postgres.py
tap-mysql 1.3.3 causing mysql taps to fail.
downgrading for now until issue is identified.
> downgrade mysql tap connector

- singer-connectors/tap-snowflake/requirements.txt
`pipelinewise-tap-snowflake` gives runtime warning messages of optional `pandas` and/or `pyarrow` not installed.
Bump `pipelinewise-tap-snowflake` to 2.0.1 that installs the required packages to avoid the runtime warning messages.
> [AP-666] Bump tap-snowflake

- docs/connectors/targets/s3_csv.rst
- pipelinewise/cli/samples/target_s3_csv.yml.sample
- singer-connectors/target-s3-csv/requirements.txt
target-s3-csv is using hard coded `aws_access_key_id` and `aws_secret_access_key` to connect to S3. This is not great because it requires hard coded credentials in tap YAMLs.
Bump to pipelinewise-target-s3-csv 1.3.0 that adds suppoort for profile based authentication and to provide credentials as environment variables.
> [AP-822] Bump target-s3-csv

- pipelinewise/cli/tap_properties.py
The config was overriding the user's own config, and already exists here: https://github.com/transferwise/pipelinewise-tap-zendesk/blob/master/tap_zendesk/default_config.json
> Override extra_config_keys with user config in tap_config

- pipelinewise/cli/commands.py
- pipelinewise/cli/utils.py
- tests/units/cli/resources/sample_log_files/tap-run-errors.log
- tests/units/cli/test_cli_utils.py
Sometimes PPW alerts not including the error. For example botocore exceptions like this one:
```
botocore.exceptions.HTTPClientError: An HTTP Client raised and unhandled exception: 'No field numbered 1 is present in this asn1crypto.keys.PublicKeyInfo'
```
Add `botocore.exceptions.` as known PPW error pattern.
> [AP-823] Add botocore.exceptions. to known error pattern list

- pipelinewise/fastsync/commons/target_snowflake.py
- singer-connectors/target-snowflake/requirements.txt
[QUOTED_IDENTIFIERS_IGNORE_CASE](https://docs.snowflake.com/en/sql-reference/parameters.html#quoted-identifiers-ignore-case) is a snowflake parameter that specifies whether the case of letters is ignored for all object identifiers in double quotes. Quoted identifiers expected as case sensitive values in multiple places, for example when creating columns with reserved words, versioning columns, getting column informations, etc.
Set  [QUOTED_IDENTIFIERS_IGNORE_CASE](https://docs.snowflake.com/en/sql-reference/parameters.html#quoted-identifiers-ignore-case) session parameter to `FALSE` when connecting to snowflake. This parameter can set for account, user and session and when it's not the default `FALSE` then target-snowflake fails.
What types of changes does your code introduce to …
> [AP-824] Set QUOTED_IDENTIFIERS_IGNORE_CASE session parameter to false

- pipelinewise/cli/schemas/target.json
- tests/units/cli/resources/target-invalid-s3-csv.yml
- tests/units/cli/resources/target-valid-s3-csv.yml
- tests/units/cli/test_cli_utils.py
JSONSchemas are not in sync with the newly introduced S3 authentication methods by https://github.com/transferwise/pipelinewise/commit/6646f537bd43f80dc98ec5694ec9839c65a80d3f and causing target-s3-csv type of targets to fail if no `aws_access_key_id` and `aws_secret_access_key` keys in the YAML
1. Update [target.json](https://github.com/transferwise/pipelinewise/blob/55471860cc2871f121ca27ee0e4e2f773ea39a78/pipelinewise/cli/schemas/target.json#L156) schema and remove the `aws_access_key_id` and `aws_secret_access_key` keys from the required list of the target-s3-csv and target-snowflake targets.
2. Add `aws_session_token` and `aws_profile` optional keys to the schemas
What types of changes does your code introduce to PipelineWise
> [AP-822] Update json schemas according to new auth methods

- singer-connectors/tap-mysql/requirements.txt
- tests/end_to_end/helpers/assertions.py
- tests/end_to_end/test_target_postgres.py
- tests/end_to_end/test_target_snowflake.py
1. The tap fails with error:
```
TypeError: argument of type 'NoneType' is not iterable
in the function tap_mysql/sync_strategies/binlog.py:row_to_singer_record
```
2. The target fails with:
```
if list(v.values())[0][0]['type'] == 'string':
TypeError: string indices must be integers
```
1. https://github.com/transferwise/pipelinewise-tap-mysql/pull/29
2. https://github.com/transferwise/pipelinewise-tap-mysql/pull/30
> [AP-742] tap-mysql: detect schema changes during log_based

- pipelinewise/cli/commands.py
Taps currently failing if stream_buffer_size is greater than 1G.
[This PR](https://github.com/transferwise/pipelinewise/pull/506/files) changed the jsonschema to allow up to 2.5G `stream_buffer_size` in the config YAML files but the tap is failing at runtime because `MAX_STREAM_BUFFER_SIZE` constant value [here](https://github.com/transferwise/pipelinewise/blob/6e2c1591e90bfd2b31d9aa8afe084388572ba223/pipelinewise/cli/commands.py#L17) doesn't allow more than 1G.
Increase the `MAX_STREAM_BUFFER_SIZE` [here](https://github.com/transferwise/pipelinewise/blob/6e2c1591e90bfd2b31d9aa8afe084388572ba223/pipelinewise/cli/commands.py#L17) to be in sync with the max allowed value in the jsonschema.
> Increase MAX_STREAM_BUFFER_SIZE to 2.5G

- docs/connectors/taps/postgres.rst
- pipelinewise/cli/samples/tap_postgres.yml.sample
A few optional parameters of tap-postgres are not documented.
Document the missing `max_run_seconds`, `logical_poll_total_seconds`, and `break_at_end_lsn` options of tap-postgres.
> [DOC] Document optional parameters of tap-postgres

- docs/connectors/taps/kafka.rst
- pipelinewise/cli/samples/tap_kafka.yml.sample
- singer-connectors/tap-kafka/requirements.txt
The current version of pipelinewise-tap-kafka 3.0.0 having some performance and functional issues.
Bump pipelinewise-tap-kafka to 4.0.0 that contains the performance improvements and fixes.
Changelog is at https://github.com/transferwise/pipelinewise-tap-kafka/blob/master/CHANGELOG.md
This is a breaking change and every kafka tap that's having the `primary_keys` option should be re-configured:
From:
```
primary_keys:
id: "$.payload.id"
type: "$.payload.type"
```
To:
```
primary_keys:
id: "/payload/id"
type: "/payload/type"
```
> [AP-786] Bump tap-kafka connector

- .circleci/config.yml
- pipelinewise/fastsync/mysql_to_postgres.py
- pipelinewise/fastsync/mysql_to_snowflake.py
- pytest.ini
- singer-connectors/tap-mysql/requirements.txt
- tests/db/tap_mysql_data.sql
- tests/end_to_end/helpers/db.py
- tests/end_to_end/test_target_postgres.py
- tests/end_to_end/test_target_snowflake.py
Currently, pipelinewise FastSync and singer replication are not aligned on how to handle `Time` column in Mysql:
* FastSync lacks mapping so Time is by default mapped to Varchar
* Singer replication on the other hand interprets `time` as a datetime.
* FastSync: map `time` to the right equivalent in targets.
* Singer replication: use https://github.com/transferwise/pipelinewise/pull/514 
> [AP-774] Properly support Mysql Time column

- docs/index.rst
Tap github is missing from tap list on the main page of the documentation.
Add tap github to the list of taps on the main page of the documentation.
> [DOC] Add github logo to main page

- pipelinewise/fastsync/postgres_to_postgres.py
- pipelinewise/fastsync/postgres_to_redshift.py
- pipelinewise/fastsync/postgres_to_snowflake.py
- tests/db/tap_postgres_data.sql
- tests/end_to_end/helpers/assertions.py
- tests/end_to_end/test-project/tap_postgres_to_pg.yml.template
- tests/end_to_end/test-project/tap_postgres_to_rs.yml.template
- tests/end_to_end/test-project/tap_postgres_to_sf.yml.template
- tests/end_to_end/test_target_postgres.py
- tests/end_to_end/test_target_redshift.py
- tests/end_to_end/test_target_snowflake.py
FastSync PG -> SF and PG -> PG map `timestamp with time zone` type columns to timestamp with timzone:
https://github.com/transferwise/pipelinewise/blob/240a9ff088871cd1f5ade2199be06d765f7cfebf/pipelinewise/fastsync/postgres_to_snowflake.py#L68
https://github.com/transferwise/pipelinewise/blob/240a9ff088871cd1f5ade2199be06d765f7cfebf/pipelinewise/fastsync/postgres_to_postgres.py#L64
The dates sent to targets are in UTC though.
There is no such issue with Singer replication. 
**Example in tap**
```
CREATE TABLE "order"
(
id serial primary key,
cvarchar varchar,
created_at timestamp default current_timestamp,
updated_at timestamp with time zone
);
insert into "order" (cvarchar, updated_at)
values ('A', '2020-01-01 08:53:56.112248-07'),
('B', '2020-08-31 08:53:56.112248+11:30'),
('C', …
```
> [AP-755] PG timestamp with TZ to target's timestamp without TZ

- singer-connectors/tap-mysql/requirements.txt
a bug was detected in ppw-tap-mysql where encountering a time type column during prepping of singer record causes the whole record to be overridden.
Use latest tap-mysql 1.3.7 with the fix 
> [Fix] time bug in tap-mysql 

- pipelinewise/fastsync/commons/tap_postgres.py
- singer-connectors/tap-postgres/requirements.txt
- tests/units/fastsync/commons/test_fastsync_tap_postgres.py
When using logical replication from a Postgres tap, Pipelinewise generates the name of the Postgres replication slot used from a combination of prefix, database name, and tap name. This does not work if any of the constituent parts contain characters that are not valid in Postgres replication slot names, or if the full generated name is more than 64 characters long.
Replace invalid characters with an underscore and truncate the generated name at 64 characters. See https://github.com/transferwise/pipelinewise/issues/529. A similar PR is open on the tap-postgres repository: https://github.com/transferwise/pipelinewise-tap-postgres/pull/63.
> [FIX] - Ensure generated Postgres replication slot name is valid

- .github/ISSUE_TEMPLATE/BUG_REPORT.md
- .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
- .github/ISSUE_TEMPLATE/QUESTION.md
- .github/ISSUE_TEMPLATE/config.yml
The github templates in this repo is using the old, deprecated Github `issue_templates`.
Adding new github templates:
* Pull Request template
* Issue templates:
- 3 issue types, (bug, feature request and question), 
- Issues are automatically labelled to make further issue analysis easier.
- TW default template to **Report a security vulnerability**, that is required for every public, open source TransferWise project. You can find an example [here](https://github.com/transferwise/pipelinewise-tap-google-analytics/security/policy). This should be available in every public repo.
- Link to the community slack channel for open discussion
This PR makes the issues page to look like this when somebody raises an issue:
> Update github templates

- docs/connectors/taps/postgres.rst
- docs/connectors/targets/postgres.rst
- pipelinewise/cli/samples/tap_postgres.yml.sample
- pipelinewise/cli/samples/target_postgres.yml.sample
PR https://github.com/transferwise/pipelinewise/pull/531 added SSL support to tap-postgres and target-postgres, but documentation not updated. 
Update documentation how to enable SSL in tap-postgres and target-postgres.
> [DOC] Document postgres SSL mode

- singer-connectors/tap-mongodb/requirements.txt
tap-mongodb doesn't support SRV urls
use latest tap-mongodb version,  [1.2.0](https://pypi.org/project/pipelinewise-tap-mongodb/)
> [AP-836] Upgrade tap-mongodb

- pipelinewise/cli/pipelinewise.py
`run_tap` and `sync_tables` commands returns exit code 0 (success), even if the tap cannot start because another tap is running or the tap cannot start because it's not enabled.
Change exit code from 0 to 1 if `run_tap` of `sync_tables` commands cannot start because another instance of the tap is already or the tap is not enabled.
> [AP-XXXX] Exit as failure when tap is running or not enabled

- singer-connectors/tap-postgres/requirements.txt
Log_Based replication in postgres doesn't properly parse data from json(b) column and the streams end up having stringified json data.
This is not in sync with other replication methods that parse json data.
https://github.com/transferwise/pipelinewise-tap-postgres/pull/70
Use ppw-tap-postgres 1.7.1
> [AP-840][FIX] Parse data from json(b) column in tap-postgres during log based replication

- pipelinewise/fastsync/commons/tap_mysql.py
- tests/db/tap_mysql_data.sql
- tests/end_to_end/test_target_postgres.py
- tests/end_to_end/test_target_snowflake.py
Hi there, I'm running into an issue replicating data from MySQL to PostgreSQL.
```ERROR: invalid byte sequence for encoding "UTF8": 0x00```
The problem is that some text fields in our MySQL database contain the NULL character which Postgres cannot stored according to [this stackoverflow post](https://stackoverflow.com/questions/1347646/postgres-error-on-insert-error-invalid-byte-sequence-for-encoding-utf8-0x0).
Notes: 
- This isn't an issue with [pipelinewise-tap-mysql](https://github.com/transferwise/pipelinewise-tap-mysql) as NULL characters are escaped to `\\u0000` when the data is converted to JSON.
This PR removes NULL characters when extracting data out text fields in a MySQL database. 
_Put an `x` in the boxes that …
> Fix issue replicating text fields with NULL characters in Tap-MySQL

- singer-connectors/tap-mysql/requirements.txt
pipelinewise-tap-mysql currently maps all non empty `bit(1)` values as `true`
Bump pipelinewise-tap-mysql to 1.3.8.
https://github.com/transferwise/pipelinewise-tap-mysql/pull/40 PR fixed the problem in tap-mysql and no change required in fastsync-mysql. 
> [AP-NNN] Bump pipelinewise-tap-mysql connector

- pipelinewise/cli/__init__.py
- pipelinewise/cli/commands.py
- pipelinewise/cli/pipelinewise.py
- pipelinewise/cli/schemas/target.json
- pipelinewise/cli/utils.py
- pylintrc
- tests/end_to_end/helpers/assertions.py
- tests/end_to_end/helpers/tasks.py
- tests/end_to_end/test_target_postgres.py
- tests/end_to_end/test_target_snowflake.py
- tests/units/cli/cli_args.py
- tests/units/cli/test_cli.py
- tests/units/cli/test_cli_utils.py
- tests/units/cli/test_commands.py
Code profiling ability missing
Add a parameter `--profiler` to pipelinewise commands, this enables profiling mode which uses Python built-in profiler cProfile to get stats on where pipelinewise is spending time.
The profiling mode also profiles the connectors and dumps their stats in separate files. 
The `pstat` files are dumped into a dynamically generated folder under `.pipelinewise/profiling`, these files can be viewed with external tools such as Pycharm or from the command line by using the `pStats` python module.
PS: Will work on documentation in a separate PR.
> [AP-495] Add --profiler optional parameter to pipelinewise commands

- docs/connectors/taps/mixpanel.rst
- pipelinewise/cli/samples/tap_mixpanel.yml.sample
- pipelinewise/cli/tap_properties.py
- singer-connectors/tap-mixpanel/requirements.txt
Tap mixpanel is de-nesting event JSONs received from the `export` and `engage` endpoints. This is cool but it's producing very wide tables and can be hard to work with it. Some database also have efficient column types to store JSONs and de-nesting is not always the preferred option.
Bump `pipelinewise-tap-mixpanel` to 1.2.0 that introduce `denest_properties` optional parameter:
* If it's `true` then JSON properties are de-nested producing wide columns in the `export` and `engage` streams.
* If it's `false` then JSON properties received from Mixpanel are kept as-is, and let the target decide how to store it: Postgres will load into `JSONB` columns, Snowflake will load into `VARIANT` column type, etc.
**The default value is `false`, so JSON properties are loaded as-is and not de-nested.** …
> [AP-345] Do not denest tap-mixpanel stream properties

- docs/connectors/targets/s3_csv.rst
- pipelinewise/cli/samples/target_s3_csv.yml.sample
KMS encryption option in target-s3-csv is not documented.
Document KMS encryption option in target-s3-csv.
> [DOC] Document KMS encryption option in target-s3-csv

- Dockerfile
Cannot build docker image if tap-oracle is selected in the connectors list:
```
docker build --build-arg connectors=tap-oracle,target-snowflake -t pipelinewise:latest .
```
Original problem reported at https://github.com/transferwise/pipelinewise/issues/570
Create `/app` before downloading oracle client
> [GITHUB-570] Fix to create docker image with tap oracle

- install.sh
PPW install script shows warning:
```
WARNING: --use-feature=2020-resolver no longer has any effect, since it is now the default dependency resolver in pip. This will become an error in pip 21.0.
```
This warning started happen since the very recently released `pip 20.3`, which comes with the new dependency resolver by default. 
Remove `--use-feature=2020-resolver` option. PPW install scripts are using the latest available pip and the install script will not fail once `pip 21.0` is available.
> Remove pip 2020-resolver feature

- pipelinewise/fastsync/commons/tap_mongodb.py
- tests/units/fastsync/commons/test_fastsync_tap_mongodb.py
- The ssl option is not taken into account when using mongodump which results in hanging connection.
Take the `ssl` value from connection config into account when using `mongodump`. The same value is already used here https://github.com/transferwise/pipelinewise/blob/5b8e9fa80f620179a21777ea427114f0ace4be48/pipelinewise/fastsync/commons/tap_mongodb.py#L123
> Add ssl support to mongodump.

- singer-connectors/tap-snowflake/requirements.txt
`snowflake-connector-python` not in sync across the components:
* `ppw-fastsync`: 2.3.6
* ` target-snowflake`: 2.3.6
* `tap-snowflake`: 2.2.9
Bump `tap-snowflake` to that comes with 2.3.6
> Bump tap-snowflake

- .circleci/config.yml
- install.sh
CI gives error messages when checking code formatting:
```
ERROR: requests 2.23.0 has requirement chardet<4,>=3.0.2, but you'll have chardet 4.0.0 which is incompatible.
ERROR: aiohttp 3.7.3 has requirement chardet<4.0,>=2.0, but you'll have chardet 4.0.0 which is incompatible.
```
And it gives a few warnings of:
```
using legacy 'setup.py install' for {some package} since package 'wheel' is not installed
```
The current script is using the original `pip` version 19, that comes with the python 3.7.7 image and `wheel` is not installed into virtual environments.
This PR upgrades `pip` to latest (>=20.3) which has dependency resolver and selects the correct version of packages and doesn't raise the errors and it installs the latest `wheel` to virtual envs.
What types of changes does your …
> Fix dependency errors and warnings

- .circleci/config.yml
- dev-project/entrypoint.sh
- docs/conf.py
- install.sh
- motd
Years in copyright messages are hard coded to 2020.
This PR makes the current year to be dynamic in [motd](https://github.com/transferwise/pipelinewise/blob/83434f36c2f82fe177cb2718c9e144ecba4f6e1b/motd) and in the footer of the [documentation](https://transferwise.github.io/pipelinewise/).
> [DOC] Use dynamic current year in copyright strings

- singer-connectors/tap-snowflake/requirements.txt
Solving a problem with usage of `LAST_QUERY_ID()` Snowflake function in ppw-tap-snowflake
use ppw-tap-snowflake v2.0.3 
> [Fix] Patch tap-snowflake to solve issue with LAST_QUERY_ID

- docs/connectors/taps/postgres.rst
- pipelinewise/cli/commands.py
- pipelinewise/cli/pipelinewise.py
- pipelinewise/fastsync/commons/tap_postgres.py
- pipelinewise/fastsync/commons/utils.py
- pipelinewise/fastsync/postgres_to_postgres.py
- pipelinewise/fastsync/postgres_to_redshift.py
- pipelinewise/fastsync/postgres_to_snowflake.py
- tests/units/fastsync/assertions.py
- tests/units/fastsync/commons/test_fastsync_tap_postgres.py
- tests/units/fastsync/commons/test_fastsync_utils.py
- tests/units/fastsync/test_postgres_to_postgres.py
- tests/units/fastsync/test_postgres_to_redshift.py
- tests/units/fastsync/test_postgres_to_snowflake.py
**AP-905** 
This is a bug in FastSync that allows running Fastsync with tables that aren't configured in the tap with the help of the arg `--tables`.
**AP-902**
When a full resync of the whole tap is triggered, PipelineWise creates a slot if it doesn’t exist.
while the full resync is taking place, if a slot already exists and occupies a lot of disk space, it will grow in size as it’s not consumed from, this can create disk space problems for small but active dbs. 
**AP-905** 
Check the list of tables provided via `tables` arg against the set of selected tables in the properties file of the tap. 
Change is in commit
**AP-902** 
Since Full resync is not making use of the slot anyway, and the latter might grow too much, add ability to drop the slot.
That is done automatically by checking the …
> [AP-902][AP-905] Drop pg replication slot in case of full re-sync of a tap.

- singer-connectors/tap-twilio/requirements.txt
Few bugs exist in the current pipelinewise-tap-twilio.
Bugs fixed in the at https://github.com/transferwise/pipelinewise-tap-twilio/blob/master/CHANGELOG.md .
Bump the tap to the latest version.
> Bump tap-twilio from 1.0.0 to 1.0.2

- singer-connectors/tap-twilio/requirements.txt
We introduced a couple of new features in the 1.1.0 tap-twilio.
- events are synched since the bookmark
- we sync more events field
- stringified json fields are converted to object 
See https://github.com/transferwise/pipelinewise-tap-twilio/blob/master/CHANGELOG.md for details
> Update twilio-tap from 1.0.2 to 1.1.0

- singer-connectors/tap-twilio/requirements.txt
pipelinewise-tap-twilio had a bug around how we get data from the state file
Bug fixed in the tap, details in https://github.com/transferwise/pipelinewise-tap-twilio/blob/master/CHANGELOG.md .
Bump the tap to the latest version.
> Bump tap-twilio from 1.1.0 to 1.1.1

- docs/connectors/taps/twilio.rst
- pipelinewise/cli/samples/tap_twilio.yml.sample
tap-twilio fails with the default documented config after pipelinewise-tap-twilio 1.1.0 :
```
time=2021-02-22 18:01:39 logger_name=singer log_level=ERROR message=ERROR 400: {"code": 20001, "message": "Invalid StartDate: 2021-02-15T00:00:00. StartDate must be a valid ISO 8601 formatted datetime string: yyyy-MM-dd'T'HH:mm:ss'Z'", "more_info": "https://www.twilio.com/docs/errors/20001", "status": 400}, REASON: BAD REQUEST
time=2021-02-22 18:01:39 logger_name=singer log_level=CRITICAL message=400: None, error code: 20001, more info: https://www.twilio.com/docs/errors/20001, ERROR: 400 Client Error: BAD REQUEST for url: https://taskrouter.twilio.com/v1/Workspaces/......./Events?StartDate=2021-02-15T00:00:00
```
Update the documentation and the sample YAML files to use ISO-8601 formatted start …
> DOC: Use ISO-8601 data formatted start data in tap-twilio

- .circleci/config.yml
- docs/connectors/taps/s3_csv.rst
- docs/connectors/targets/redshift.rst
- docs/connectors/targets/s3_csv.rst
- docs/connectors/targets/snowflake.rst
- pipelinewise/cli/samples/tap_s3_csv.yml.sample
- pipelinewise/cli/samples/target_redshift.yml.sample
- pipelinewise/cli/samples/target_s3_csv.yml.sample
- pipelinewise/cli/samples/target_snowflake.yml.sample
- pipelinewise/fastsync/commons/tap_s3_csv.py
- pipelinewise/fastsync/s3_csv_to_postgres.py
- pipelinewise/fastsync/s3_csv_to_redshift.py
- pipelinewise/fastsync/s3_csv_to_snowflake.py
- pylintrc
- tests/units/fastsync/commons/test_fastsync_tap_s3_csv.py
1. 
Singer replication from s3 csv has support for auth via AWS profile or IAM role. FastSync doesn’t which means we cannot have a tap s3 csv unless it has credentials.
The error we get is: 
```
Config is missing required keys: ['aws_access_key_id', 'aws_secret_access_key']
```
2. Documentation around using AWS profile to authenticate to S3 bucket is not super clear.
1. Add support for auth via AWS profile to FastSync `tap-s3-csv` so as it is in sync with its Singer counterpart.
2. Update documentation
> AP-965 add support for auth to s3 source via aws profile to FastSync

- pipelinewise/fastsync/commons/target_redshift.py
- pipelinewise/fastsync/commons/target_snowflake.py
- pipelinewise/fastsync/commons/utils.py
- pipelinewise/fastsync/mongodb_to_postgres.py
- pipelinewise/fastsync/mongodb_to_snowflake.py
- pipelinewise/fastsync/mysql_to_postgres.py
- pipelinewise/fastsync/mysql_to_redshift.py
- pipelinewise/fastsync/mysql_to_snowflake.py
- pipelinewise/fastsync/postgres_to_postgres.py
- pipelinewise/fastsync/postgres_to_redshift.py
- pipelinewise/fastsync/postgres_to_snowflake.py
- pipelinewise/fastsync/s3_csv_to_postgres.py
- pipelinewise/fastsync/s3_csv_to_redshift.py
- pipelinewise/fastsync/s3_csv_to_snowflake.py
- tests/units/fastsync/assertions.py
- tests/units/fastsync/commons/test_fastsync_utils.py
Filenames in fastsync are not unique enough. If two taps with the same table name started at the same time then it's possible that they're using the same export file names, causing file name collisions and failures.
Generate more unique file names:
* Pattern: `pipelinewise_<tap_id>_<table>_<timestamp_with_milliseconds>_fastsync_<random_string>.csv.gz`
* Sample generated filename: `pipelinewise_tap_table_20210316-111338-878470_fastsync_L5C6VG9W.csv.gz`
> [AP-975] Use unique file names in fastsync to avoid file name collision

- singer-connectors/tap-twilio/requirements.txt
pipelinewise-tap-twilio had a bug around missing data from chat_channels, this PR addresses that one
Bug fixed in the tap, details in https://github.com/transferwise/pipelinewise-tap-twilio/blob/master/CHANGELOG.md .
Bump the tap to the latest version.
> Bump tap-twilio from 1.1.1 to 1.1.2

- .circleci/config.yml
Upload step fails with missing url option
Set the environment variable: DEPLOY_REGISTRY_URL in the config.
It has also been added to CircleCI UI
> [CI] Fix upload docker image step

- .circleci/config.yml
Looks like `DEPLOY_REGISTRY_URL` is messing up the docker image name.
Remove it and let it be picked up dynamically from the context
> [CI] Fix docker deploy step

- .github/workflows/dockerhub.yml
PPW releases not published to dockerhub automatically at https://hub.docker.com/r/transferwiseworkspace/pipelinewise
Build and push every published releases to dockerhub. 
> [AP-862] Publish releases to dockerhub

- singer-connectors/tap-s3-csv/requirements.txt
Current tap-s3-csv uses old dependencies 
Uses latest version with bumped dependencies
> AP-NNN Bump tap-s3-csv to 1.2.1

- pipelinewise/cli/config.py
- pipelinewise/fastsync/commons/target_snowflake.py
- pipelinewise/fastsync/mongodb_to_snowflake.py
- pipelinewise/fastsync/mysql_to_snowflake.py
- pipelinewise/fastsync/postgres_to_snowflake.py
- tests/end_to_end/helpers/env.py
- tests/end_to_end/test-project/tap_postgres_to_sf_archive_load_files.yml.template
- tests/end_to_end/test_target_snowflake.py
- tests/units/cli/test_config.py
- tests/units/fastsync/commons/test_fastsync_target_snowflake.py
https://transferwise.atlassian.net/browse/AP-1011
When enabled, this feature will result in PipelineWise load files being copied to a separate folder for archival.
See https://github.com/transferwise/pipelinewise-target-snowflake/pull/178 for same feature in target-snowflake.
Original grooming document (slightly outdated now):
https://docs.google.com/document/d/11UTlmWVJS9aGickmyxpXOUhrv4RTPnm8zip_IqeR2J0/edit?ts=609e4106
> AP1011 archive_load_files in fastsync

- singer-connectors/tap-postgres/requirements.txt
PostgreSQL has a new, partition relation type. Discovery is not currently selecting these relations.
Improve discovery to support partition relation type.
> Bump tap-postgres from 1.7.1 to 1.8.0

- singer-connectors/target-snowflake/requirements.txt
- tests/end_to_end/test_target_snowflake.py
Archiving load files feature for fastsync is already merged to this repo (https://github.com/transferwise/pipelinewise/pull/717). The equivalent feature added to target-snowflake as well but the new version is not included in this repo. (https://github.com/transferwise/pipelinewise-target-snowflake/pull/178)
Bump target snowflake to latest to include `archive_load_files` option. 
The PR also fixing e2e tests where multiple archive files expected, one from fastsync and one from target-snowflake
> Bump target-snowflake from 1.12.0 to 1.13.0

- tests/end_to_end/test_target_snowflake.py
[test_resync_pg_to_sf_with_split_large_files](test_resync_pg_to_sf_with_split_large_files) end-to-end test is always running regardless if snowflake connection is enabled or not.
Run this test only if snowflake is configured by using the same annotation that we use in other tests.
> Run snowflake e2e test only when it's enabled

- pipelinewise/fastsync/commons/target_bigquery.py
- tests/units/fastsync/commons/test_fastsync_target_bigquery.py
BigQuery in fastsync mode is ignoring the location project config and writing to the default location
Change the open connection function call to use the location added in the target yml file
> add location config to bigquery fastsync

- pipelinewise/fastsync/s3_csv_to_bigquery.py
s3 date type is detected as a string by the incremental load. Fastsync should do the same
Change the mapping of date s3 csv type to STRING
> fix s3 date type mapping in bigquery fastsync

- pipelinewise/cli/schemas/tap.json
As we started using the archive_load_files feature to archive historical fin_business_event records to S3, we ran into some limits imposed by PipelineWise, specifically `batch_size_rows` and `split_file_chunk_size_mb`.
Based on discussions with @koszti, they are both more a "sane maximum" than something based on actual limitations.
* Increase `batch_size_rows` from 1M to 5M
* We observed 1M batch size resulting in ~36mb gzipped csv files in S3, whereas 100-200mb is considered more optimal for Snowflake.
* Increase `split_file_chunk_size_mb` from 2500 to 5000
* We would have preferred even larger files, but S3 copy command imposes a limit of 5,368,709,120 bytes
> Increase max batch_size_rows and split_file_chunk_size_mb

- pipelinewise/cli/utils.py
When a tap/target is being validated against json schema, the object gets logged if it's invalid thus exposing any credentials in it.
Do not log the object
> AP-NNN Fix: Do not log invalid json object

- singer-connectors/tap-github/requirements.txt
Github tap has a bugfix to do not do rate throttling during discovery but it's not linked to PPW.
Bump pipelinewise-tap-github from 1.0.0 to 1.0.1
> Bump tap-github from 1.0.0 to 1.0.1

- singer-connectors/tap-github/requirements.txt
Github tap has a bugfix to do not do rate throttling during discovery but it's not linked to PPW.
Bump pipelinewise-tap-github from 1.0.1 to 1.0.2
> Bump pipelinewise-tap-github from 1.0.1 to 1.0.2

- install.sh
- singer-connectors/tap-adwords/pre_requirements.txt
- singer-connectors/tap-adwords/requirements.txt
`tap-adwords` causes connection workflow not be successful and crashes on it.
`tap-adwords` required version `17.0.0` of `googleads` and this version uses `use_2to3` which is removed in `setuptools` > `58.0.0`, so to be able to install `googleads==17.0.0` we need to downgrade `setuptools`
> [AP-1059] downgrade setuptools to support use_2to3

- pipelinewise/fastsync/commons/tap_postgres.py
- tests/db/tap_postgres_data.sql
PG Source can contain dates outside of the range [0001-01-01, 9999-12-31].
These dates cause FS and Singer replication to fail or results in invalid data.
Note: I haven't been able to produce a date < 0001-01-01 in postgres, but there could be some circumstance I'm not aware of, plus I wanted to keep consistent with the existing fix for timestamps so I made my change with that in mind.
I fixed a similar issue [in pipelinewise-tap-postgres](https://github.com/transferwise/pipelinewise-tap-postgres/pull/122#issuecomment-919781272), and was asked to take a stab at this fix.
I used [the fix for for handling out of range timestamps](https://github.com/transferwise/pipelinewise/pull/521) as a template.
I don't use pipelinewise so I'm not sure of the best way to test this, but I ran the modified …
> Handle dates out of range in PG source

- tests/units/cli/test_cli.py
In some cases `proc.info['cmdline']` can be `None` and it causes this test crashes.
join the `proc.info['cmdline']` if it is not `None` otherwise an empty string.
> [AP-1058] fixed proc.info parsing in a case cmdline is None!

- tests/end_to_end/helpers/assertions.py
- tests/end_to_end/helpers/env.py
- tests/end_to_end/test-project/tap_mongodb_to_sf.yml.template
- tests/end_to_end/test-project/tap_mysql_to_sf.yml.template
- tests/end_to_end/test-project/tap_mysql_to_sf_buffered_stream.yml.template
- tests/end_to_end/test-project/tap_mysql_to_sf_split_large_files.yml.template
- tests/end_to_end/test-project/tap_postgres_to_sf.yml.template
- tests/end_to_end/test-project/tap_postgres_to_sf_archive_load_files.yml.template
- tests/end_to_end/test-project/tap_postgres_to_sf_split_large_files.yml.template
- tests/end_to_end/test-project/tap_s3_csv_to_sf.yml.template
- tests/end_to_end/test_target_snowflake.py
e2e test with target Snowflake are susceptible to collision when running at the same time from multiple machine/branch and cause CI failures.
Generating a UUID string which will be added to the name of schema as a postfix. in this case each test suite will have a unique SF schema.
> [AP-992] make a postfix for sf schemas in e2e

- Dockerfile
- Dockerfile.barebone
- dev-project/entrypoint.sh
- docs/connectors/taps/mongodb.rst
- pipelinewise/fastsync/commons/tap_mongodb.py
- setup.py
- singer-connectors/tap-mongodb/requirements.txt
- tests/units/fastsync/commons/test_fastsync_tap_mongodb.py
`tap-mongodb` does not support MongoDB Atlas in fastsync mode.
Copy approach from `pipelinewise-tap-mongodb`: build `MongoClient` connection string both for API client and `mongodump`.
> Implement support for MongoDB Atlas fastsync

- singer-connectors/tap-postgres/requirements.txt
- singer-connectors/tap-s3-csv/requirements.txt
- singer-connectors/target-snowflake/requirements.txt
Bumps: 
- pipelinewise-target-snowflake to 1.15.0
- pipelinewise-tap-s3-csv to 1.2.3
- pipelinewise-tap-postgres to 1.8.2
> [AP-0] Bump connectors

- singer-connectors/tap-kafka/requirements.txt
`pipelinewise-tap-kafka-5.0.0` introduced some new feature that we want to start using.
Bump `pipelinewise-tap-kafka` from `4.0.1` to `5.0.0`.
> Bump pipelinewise-tap-kafka from 4.0.1 to 5.0.0

- singer-connectors/tap-kafka/requirements.txt
`pipelinewise-tap-kafka 5.0.0` doesn't include some required modules and producing runtime error: `ModuleNotFoundError: No module named 'tap_kafka.serialization':`
Bump `pipelinewise-tap-kafka` from `5.0.0` to `5.0.1` which includes the fix.
>  Bump tap-kafka from 5.0.0 to 5.0.1

- singer-connectors/tap-kafka/requirements.txt
`pipelinewise-tap-kafka` 5.1.0 introducing some fixes and features that we may want to use, like protobuf support.
Bump `pipelinewise-tap-kafka` from `5.0.1` to `5.1.0`.
> [AP-996] Bump pipelinewise-tap-kafka from 5.0.1 to 5.1.0

- docs/connectors/taps/kafka.rst
- pipelinewise/cli/samples/tap_kafka.yml.sample
- singer-connectors/tap-kafka/requirements.txt
[pipelinewise-tap-kafka](github.com/transferwise/pipelinewise-tap-kafka) introduced some changes in the tap YAML format that's not in sync with the online documentation.
Document [pipelinewise-tap-kafka 5.x](github.com/transferwise/pipelinewise-tap-kafka) YAML format.
> [DOC] Document tap kafka YAML format after 5.x

- pytest.ini
- tests/end_to_end/helpers/env.py
- tests/end_to_end/test_target_snowflake.py
Albeit SF credentials are provided in the CI environment, Github doesn't not share these credentials with PRs from forked repos, hence the SF tests are skipped but fail in the last step,
the issue lies in the teardown step when it's trying to clean up SF but cannot connect to it.
* Create a class fixture to skip all tests if SF is not configured
* Only teardown if SF is configured
> Fix: e2e tests fail when SF credentials are not present

- .github/workflows/linter.yml
- .github/workflows/tests.yml
- setup.py
ujson 4.x has a vulnerability [CVE-2021-45958](https://github.com/advisories/GHSA-fh56-85cw-5pq6):
https://github.com/transferwise/pipelinewise/security/dependabot/setup.py/ujson/open
Bump ujson from 4.x to 5.1.0
> Bump ujson from 4.x to 5.1.0

- pipelinewise/cli/commands.py
- pipelinewise/cli/pipelinewise.py
- tests/units/cli/test_commands.py
- tests/units/cli/test_config_validation.py
- The `namedtuples` with overridden `__init__` methods are really, really ugly.
- Use `dataclasses`
_Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. 
If it fixes a bug or resolves a feature request, be sure to link to that issue._
> Convert `NamedTuple` to `dataclass`

- pipelinewise/cli/schemas/tap.json
For extremely large tables the current limits can result in insufficient splits being allowed.
- Relax the upper limit to `99,999`. This is the largest number which can be represented with the 5 digit file part numbering scheme.
_Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. 
If it fixes a bug or resolves a feature request, be sure to link to that issue._
> Relax upper limit on `split_file_max_chunks`

- .github/workflows/tests.yml
- pipelinewise/fastsync/commons/tap_postgres.py
- pipelinewise/fastsync/postgres_to_postgres.py
- singer-connectors/tap-postgres/requirements.txt
- tests/db/tap_postgres_data.sql
- tests/end_to_end/test-project/tap_postgres_to_pg.yml.template
- tests/end_to_end/test-project/tap_postgres_to_sf.yml.template
- tests/end_to_end/test-project/tap_postgres_to_sf_split_large_files.yml.template
- tests/units/fastsync/commons/test_fastsync_tap_postgres.py
https://github.com/transferwise/pipelinewise/issues/806
The bookmark for incremental is also wrong, it's returning a null replication key value because there is no data.
Add condition on the existence of exported file, and only import into target PG if this file exists.
Return empty bookmarks for empty tables.
> AP-1072|Issue:806 FastSync Pg to Pg fails on empty tables

- pipelinewise/cli/pipelinewise.py
Since the implementation of a PID file, checking these log files should not longer be done.
Removed log file status checking to decide if a tap can be started
> [AP-1104] Ignore log file status when deciding if a tap can be started

- tests/end_to_end/test-project/tap_mysql_to_sf_split_large_files.yml.template
If E2E test `test_resync_mariadb_to_sf_with_split_large_files` is run independently, then it fails. But it passes if it's run as a part of the entire test suite.
Fixing `tap_mysql_to_sf_split_large_files.yml.template` so that the test can succeed if run independently also.
> fix tap_mysql_to_sf_split_large_files.yml.template

- docs/connectors/taps/kafka.rst
- singer-connectors/tap-kafka/requirements.txt
There is a new release for tap-kafka (v7.0.0). 
Note: the change is breaking for some specific taps and is not backwards compatible out-of-the-box.
Bumping tap-kafka requirement to v7.0.0 as well as updating the documentation to reflect the change.
> RULES-655 bumping tap-kafka version

- pipelinewise/cli/schemas/tap.json
Tap json schema is currently misaligned with the changes introduced in tap-kafka v7.0.0 (and the subsequent bump of requirement https://github.com/transferwise/pipelinewise/pull/928).
Added new property, `use_message_key`, to the tap schema.
> RULES-655 updating tap json schema

- singer-connectors/tap-mysql/requirements.txt
There is a bug when switch a mariadb tap to use GTID, gtid lookup runs into an edge case.
see https://github.com/transferwise/pipelinewise-tap-mysql/pull/102
patch tap-mysql
> AP-1183: patch tap-mysql

- .github/workflows/e2e_tests.yml
- singer-connectors/target-s3-csv/requirements.txt
We're running into some issues in target-s3-csv, latest release of the target has the fix
https://github.com/transferwise/pipelinewise-target-s3-csv/releases/tag/v2.0.0
end to end tests are failing due to this PR:  https://github.com/transferwise/pipelinewise/pull/959
- Bump target s3 csv to v2
- create .env file out of the the template file so that end 2 end tests pass.
- x ] Description above provides context of the change
> AP-1226 bump target-s3-csv

- pipelinewise/cli/commands.py
- tests/units/cli/resources/test_partial_sync/target_snowflake/tap_mysql/properties.json
- tests/units/cli/resources/test_partial_sync/target_snowflake/tap_mysql/transformation.json
- tests/units/cli/test_partial_sync.py
It could not find the table if there is any space in the name
fixing the command generation to have double quotes around the table name
> [AP-1250] Fix for table with space in the name

- pipelinewise/fastsync/mysql_to_bigquery.py
- pipelinewise/fastsync/mysql_to_postgres.py
- pipelinewise/fastsync/mysql_to_redshift.py
- pipelinewise/fastsync/mysql_to_snowflake.py
In FastSync mysql->X , two connections (buffered and unbuffered) are opened for each table that needs fastsync, if a failure happens before the `close_connections` method is called, these  orphaned connections end up being aborted by the server which shows up in the db logs like so: 
```
pipelinewise_dev_mysql_source | 2022-10-05 12:24:25 140669979453184 [Warning] Aborted connection 129 to db: 'unconnected' user: 'pipelinewise' host: '192.168.56.7' (Got an error reading communication packets)
pipelinewise_dev_mysql_source | 2022-10-05 12:24:25 140670126831360 [Warning] Aborted connection 136 to db: 'unconnected' user: 'pipelinewise' host: '192.168.56.7' (Got an error reading communication packets)
pipelinewise_dev_mysql_source | 2022-10-05 12:24:25 140670127138560 [Warning] Aborted …
```
> AP-1101: Close mysql/mariab connections in FastSync 

- dev-project/docker-compose.yml
- dev-project/pg/Dockerfile
- docs/connectors/taps/postgres.rst
- singer-connectors/tap-postgres/requirements.txt
Tap-postgres now supports using format-version 2 wen consuming WAL using wal2json  
Bump tap-postgres and update test container to have wal2json >= v2.3 
> AP-1276 Bump tap-postgres to use wal2json format version 2

- pipelinewise/cli/utils.py
- tests/units/cli/test_cli_utils.py
A small issue was introduced by https://github.com/transferwise/pipelinewise/pull/1058
where `silentremove` function is called on a directory but this function only supports files
Extend `silentremove` to delete folders too.
> Extend silentremove to support deleting folders

- singer-connectors/tap-slack/requirements.txt
Fetching users from slack runs into rate limiting 
Bump tap-slack patch to latest which has a fix
https://github.com/transferwise/pipelinewise-tap-slack/releases/tag/v1.1.1
> AP-1335: Bump tap-slack to latest patch

- CHANGELOG.md
- setup.py
- singer-connectors/tap-mysql/requirements.txt
https://github.com/transferwise/pipelinewise-tap-mysql/pull/149
Fetch the latest ppw-tap-mysql with the fix
> AP-1435 Bump tap-mysql and prep for release

- dev-project/pg/Dockerfile
Making the docker image for PG is failing because of wal2json
using the compatible llvm and clang version for making wal2json
> [AP-1515] fix for wal2json making

- pipelinewise/cli/pipelinewise.py
- tests/units/cli/test_cli.py
Resync triggered unnecessarily for an existing table
fixed the method which is used to select the list of tables need to be synced.
> [AP-1485] fix for unwanted sync trigger for tables

- pipelinewise/fastsync/partialsync/mysql_to_snowflake.py
- pipelinewise/fastsync/partialsync/postgres_to_snowflake.py
A tap setup to replicate LOG_BASED from a PG source should create the replication slot before starting the partial sync … or else CDC replication will fail later.
have the same order for calling the method same as fast sync.
> [AP-1519]fixed replication slot creation

- singer-connectors/tap-s3-csv/requirements.txt
Bump pipelinewise_tap_s3_csv from 3.0.0 to 3.0.1
> [AP-1500] Bump pipelinewise_tap_s3_csv from 3.0.0 to 3.0.1

- pipelinewise/utils.py
- tests/units/test_utils.py
it is running count(*) against tables which DBE is not happy about!
Remove counting row completely since it is not used at all for making decision
>h2. Context
>
>
>
>
>
>
[AP-1800]: https://transferwise.atlassian.net/browse/AP-1800?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [AP-1800] remove counting rows in checking for resync

- .github/tw-rules.yaml
- .github/workflows/connectors.yml
[AP-1765](https://transferwise.atlassian.net/browse/AP-1765)
Add TW Rules definition
[AP-1765]: https://transferwise.atlassian.net/browse/AP-1765?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add TW Rules definition

- .github/workflows/connectors.yml
- Makefile
[AP-1765](https://transferwise.atlassian.net/browse/AP-1765) Makefile parameter to avoid Warning
[AP-1765]: https://transferwise.atlassian.net/browse/AP-1765?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Makefile parameter to avoid Warning

- dev-project/docker-compose.yml
- dev-project/mongo/create-pipelinewise-user.sh
- docs/user_guide/resync.rst
- pipelinewise/cli/__init__.py
- pipelinewise/cli/pipelinewise.py
- scripts/publish_docs.sh
- tests/units/cli/cli_args.py
- tests/units/cli/test_cli.py
_Describe the problem your PR is trying to solve_
>h2. Problem
>
>Please give context of the problem and as much details as possible.
>
>h2. Suggested solution(s)
>
>Any ideas on how to solve this or how to go about investigating it
[AP-1927]: https://transferwise.atlassian.net/browse/AP-1927?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [AP-1927] added new argument for selecting replication method to sync tables

- CHANGELOG.md
- setup.py
Prepare for Release 0.67.0
- Fix map date column to correct Postgres type
- New argument for sync tables to select replication method
> Prepare for Release 0.67.0

- docs/user_guide/cli.rst
- pipelinewise/cli/__init__.py
- pipelinewise/cli/pipelinewise.py
- tests/units/cli/resources/test_reset_state/config.json
- tests/units/cli/resources/test_reset_state/target_foo/tap_pg/state.json
- tests/units/cli/test_reset_state.py
Added the new command `reset_state` to reset state file for log-based tables in PostgresSQL taps.
>h2. Context
>
>Please give context of the task, the problem that it solves, how impactful it is ..etc
>
>h2. Suggested Implementation(s)
>
>Any ideas on solutions or implementation
[AP-2038]: https://transferwise.atlassian.net/browse/AP-2038?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [AP-2038] implementing reset_state command

- CHANGELOG.md
- setup.py
Prepare for release 0.68.0
- Bump `requests` from `2.20.0` to `2.32.2` in `/singer-connectors/tap-github`
- Add `reset_state` command for PG taps
> Prepare for release 0.68.0

- .github/workflows/connectors.yml
- .github/workflows/e2e_tests.yml
- .github/workflows/lint_unit_tests.yml
- docs/user_guide/cli.rst
- pipelinewise/cli/pipelinewise.py
- pipelinewise/cli/schemas/config.json
- tests/units/cli/resources/test_reset_state/config.json
- tests/units/cli/resources/test_reset_state/target_foo/tap_mysql/config.json
- tests/units/cli/resources/test_reset_state/target_foo/tap_mysql/state.json
- tests/units/cli/test_reset_state.py
support reset_state command for mysql taps 
https://transferwise.atlassian.net/browse/AP-2075
> [AP-2075] reset_state for mysql type taps

- CHANGELOG.md
- setup.py
- singer-connectors/target-snowflake/CHANGELOG.md
- singer-connectors/target-snowflake/setup.py
These changes:
- upgrade snowflake-connector-python[pandas] from `3.0.4` to `3.15.0` to fix the error: "snowflake.connector.errors.OperationalError: 254007: The certificate is revoked or could not be validated: hostname=[sfc-eu-ds1-customer-stage.s3.eu-central-1.amazonaws.com](http://sfc-eu-ds1-customer-stage.s3.eu-central-1.amazonaws.com/)"
> Upgrade snowflake-connector-python[pandas] from 3.0.4 to 3.15.0 to fix snowflake failures
